{
 "title": "CPU_RAM_DISK_NETWORK",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MIN-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DB-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Report Service-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolr-rp50.*/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "FinstreamAdapter-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvola-ap50.*/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RsAccess-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5001wv\" or r[\"host\"] == \"ltvolt-ap5002wv\" or r[\"host\"] == \"ltvolt-ap5003wv\" or r[\"host\"] == \"ltvolt-ap5004wv\" or r[\"host\"] == \"ltvolt-ap5005wv\" or r[\"host\"] == \"ltvolt-ap5006wv\" or r[\"host\"] == \"ltvolt-ap5007wv\" or r[\"host\"] == \"ltvolt-ap5008wv\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TelebankCommands-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5009wv\" or r[\"host\"] == \"ltvolt-ap5010wv\" or r[\"host\"] == \"ltvolt-ap5011wv\" or r[\"host\"] == \"ltvolt-ap5012wv\" or r[\"host\"] == \"ltvolt-ap5013wv\" or r[\"host\"] == \"ltvolt-ap5014wv\" or r[\"host\"] == \"ltvolt-ap5015wv\" or r[\"host\"] == \"ltvolt-ap5016wv\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Front-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltibrb-tm5002wv\" or r[\"host\"] == \"ltibrb-tm5003wv\" or r[\"host\"] == \"ltibrb-tm5004wv\" or r[\"host\"] == \"ltibrb-tm5005wv\" or r[\"host\"] == \"ltibrb-tm5006wv\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cache-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltibrb-we5002wv\" or r[\"host\"] == \"ltibrb-we5003wv\" or r[\"host\"] == \"ltibrb-we5004wv\" or r[\"host\"] == \"ltibrb-we5005wv\" or r[\"host\"] == \"ltibrb-we5006wv\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "STUBS-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolz-mk50.*/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MTE-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolp-ap5001wv/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ProcessClusters-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Processor_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5007wv\" or r[\"host\"] == \"ltvolp-ap5008wv\" or r[\"host\"] == \"ltvolp-ap5009wv\" or r[\"host\"] == \"ltvolp-ap5010wv\" or r[\"host\"] == \"ltvolp-ap5011wv\" or r[\"host\"] == \"ltvolp-ap5012wv\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"_Total\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "MIN-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DB-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Report Service-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolr-rp50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "FinstreamAdapter-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvola-ap50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RsAccess-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5001wv\" or r[\"host\"] == \"ltvolt-ap5002wv\" or r[\"host\"] == \"ltvolt-ap5003wv\" or r[\"host\"] == \"ltvolt-ap5004wv\" or r[\"host\"] == \"ltvolt-ap5005wv\" or r[\"host\"] == \"ltvolt-ap5006wv\" or r[\"host\"] == \"ltvolt-ap5007wv\" or r[\"host\"] == \"ltvolt-ap5008wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TelebankCommands-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5009wv\" or r[\"host\"] == \"ltvolt-ap5010wv\" or r[\"host\"] == \"ltvolt-ap5011wv\" or r[\"host\"] == \"ltvolt-ap5012wv\" or r[\"host\"] == \"ltvolt-ap5013wv\" or r[\"host\"] == \"ltvolt-ap5014wv\" or r[\"host\"] == \"ltvolt-ap5015wv\" or r[\"host\"] == \"ltvolt-ap5016wv\")\r\n   |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Front-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltibrb-tm5002wv\" or r[\"host\"] == \"ltibrb-tm5003wv\" or r[\"host\"] == \"ltibrb-tm5004wv\" or r[\"host\"] == \"ltibrb-tm5005wv\" or r[\"host\"] == \"ltibrb-tm5006wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cache-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltibrb-we5002wv\" or r[\"host\"] == \"ltibrb-we5003wv\" or r[\"host\"] == \"ltibrb-we5004wv\" or r[\"host\"] == \"ltibrb-we5005wv\" or r[\"host\"] == \"ltibrb-we5006wv\")   |> filter(fn: (r) => r[\"objectname\"] == \"Memory\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "STUBS-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolz-mk50.*/)\r\n   |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MTE-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolp-ap5001wv/)\r\n   |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ProcessClusters-Available bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Available_Bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5007wv\" or r[\"host\"] == \"ltvolp-ap5008wv\" or r[\"host\"] == \"ltvolp-ap5009wv\" or r[\"host\"] == \"ltvolp-ap5010wv\" or r[\"host\"] == \"ltvolp-ap5011wv\" or r[\"host\"] == \"ltvolp-ap5012wv\")\r\n   |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "DISK Percent Write Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "MIN-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DB-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Report Service-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolr-rp50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "FinstreamAdapter-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvola-ap50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RsAccess-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5001wv\" or r[\"host\"] == \"ltvolt-ap5002wv\" or r[\"host\"] == \"ltvolt-ap5003wv\" or r[\"host\"] == \"ltvolt-ap5004wv\" or r[\"host\"] == \"ltvolt-ap5005wv\" or r[\"host\"] == \"ltvolt-ap5006wv\" or r[\"host\"] == \"ltvolt-ap5007wv\" or r[\"host\"] == \"ltvolt-ap5008wv\")\r\n   |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TelebankCommands-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5009wv\" or r[\"host\"] == \"ltvolt-ap5010wv\" or r[\"host\"] == \"ltvolt-ap5011wv\" or r[\"host\"] == \"ltvolt-ap5012wv\" or r[\"host\"] == \"ltvolt-ap5013wv\" or r[\"host\"] == \"ltvolt-ap5014wv\" or r[\"host\"] == \"ltvolt-ap5015wv\" or r[\"host\"] == \"ltvolt-ap5016wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Front-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n    |> filter(fn: (r) => r[\"host\"] == \"ltibrb-tm5002wv\" or r[\"host\"] == \"ltibrb-tm5003wv\" or r[\"host\"] == \"ltibrb-tm5004wv\" or r[\"host\"] == \"ltibrb-tm5005wv\" or r[\"host\"] == \"ltibrb-tm5006wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "STUBS-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolz-mk50.*/)\r\n |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cache-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltibrb-we5002wv\" or r[\"host\"] == \"ltibrb-we5003wv\" or r[\"host\"] == \"ltibrb-we5004wv\" or r[\"host\"] == \"ltibrb-we5005wv\" or r[\"host\"] == \"ltibrb-we5006wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MTE-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5001wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ProcessClusters-Percent Disk Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Write_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5007wv\" or r[\"host\"] == \"ltvolp-ap5008wv\" or r[\"host\"] == \"ltvolp-ap5009wv\" or r[\"host\"] == \"ltvolp-ap5010wv\" or r[\"host\"] == \"ltvolp-ap5011wv\" or r[\"host\"] == \"ltvolp-ap5012wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "DISK Percent Read Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "MIN-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DB-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Report Service-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolr-rp50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "FinstreamAdapter-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvola-ap50.*/)\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RsAccess-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5001wv\" or r[\"host\"] == \"ltvolt-ap5002wv\" or r[\"host\"] == \"ltvolt-ap5003wv\" or r[\"host\"] == \"ltvolt-ap5004wv\" or r[\"host\"] == \"ltvolt-ap5005wv\" or r[\"host\"] == \"ltvolt-ap5006wv\" or r[\"host\"] == \"ltvolt-ap5007wv\" or r[\"host\"] == \"ltvolt-ap5008wv\")\r\n   |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cache-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltibrb-we5002wv\" or r[\"host\"] == \"ltibrb-we5003wv\" or r[\"host\"] == \"ltibrb-we5004wv\" or r[\"host\"] == \"ltibrb-we5005wv\" or r[\"host\"] == \"ltibrb-we5006wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "STUBS-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolz-mk50.*/)\r\n |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Front-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n    |> filter(fn: (r) => r[\"host\"] == \"ltibrb-tm5002wv\" or r[\"host\"] == \"ltibrb-tm5003wv\" or r[\"host\"] == \"ltibrb-tm5004wv\" or r[\"host\"] == \"ltibrb-tm5005wv\" or r[\"host\"] == \"ltibrb-tm5006wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cache-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltibrb-we5002wv\" or r[\"host\"] == \"ltibrb-we5003wv\" or r[\"host\"] == \"ltibrb-we5004wv\" or r[\"host\"] == \"ltibrb-we5005wv\" or r[\"host\"] == \"ltibrb-we5006wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MTE-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5001wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TelebankCommands-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5009wv\" or r[\"host\"] == \"ltvolt-ap5010wv\" or r[\"host\"] == \"ltvolt-ap5011wv\" or r[\"host\"] == \"ltvolt-ap5012wv\" or r[\"host\"] == \"ltvolt-ap5013wv\" or r[\"host\"] == \"ltvolt-ap5014wv\" or r[\"host\"] == \"ltvolt-ap5015wv\" or r[\"host\"] == \"ltvolt-ap5016wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ProcessClusters-Percent Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Read_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5007wv\" or r[\"host\"] == \"ltvolp-ap5008wv\" or r[\"host\"] == \"ltvolp-ap5009wv\" or r[\"host\"] == \"ltvolp-ap5010wv\" or r[\"host\"] == \"ltvolp-ap5011wv\" or r[\"host\"] == \"ltvolp-ap5012wv\")\r\n  |> filter(fn: (r) => r[\"objectname\"] == \"LogicalDisk\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "DISK TIME", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "MIN-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DB-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Report Service-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolr-rp50.*/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "FinstreamAdapter-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvola-ap50.*/)\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RsAccess-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5001wv\" or r[\"host\"] == \"ltvolt-ap5002wv\" or r[\"host\"] == \"ltvolt-ap5003wv\" or r[\"host\"] == \"ltvolt-ap5004wv\" or r[\"host\"] == \"ltvolt-ap5005wv\" or r[\"host\"] == \"ltvolt-ap5006wv\" or r[\"host\"] == \"ltvolt-ap5007wv\" or r[\"host\"] == \"ltvolt-ap5008wv\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TelebankCommands-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n   |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5009wv\" or r[\"host\"] == \"ltvolt-ap5010wv\" or r[\"host\"] == \"ltvolt-ap5011wv\" or r[\"host\"] == \"ltvolt-ap5012wv\" or r[\"host\"] == \"ltvolt-ap5013wv\" or r[\"host\"] == \"ltvolt-ap5014wv\" or r[\"host\"] == \"ltvolt-ap5015wv\" or r[\"host\"] == \"ltvolt-ap5016wv\")\r\n |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Front-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltibrb-tm5002wv\" or r[\"host\"] == \"ltibrb-tm5003wv\" or r[\"host\"] == \"ltibrb-tm5004wv\" or r[\"host\"] == \"ltibrb-tm5005wv\" or r[\"host\"] == \"ltibrb-tm5006wv\")\r\n  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "STUBS-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n |> filter(fn: (r) => r[\"host\"] =~ /ltvolz-mk50.*/)  |> filter(fn: (r) => r[\"instance\"] == \"C:\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cache-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 229 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltibrb-we5002wv\" or r[\"host\"] == \"ltibrb-we5003wv\" or r[\"host\"] == \"ltibrb-we5004wv\" or r[\"host\"] == \"ltibrb-we5005wv\" or r[\"host\"] == \"ltibrb-we5006wv\")\r\n |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MTE-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 229 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5001wv\")\r\n |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ProcessClusters-Disk  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 237 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Percent_Disk_Time\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5007wv\" or r[\"host\"] == \"ltvolp-ap5008wv\" or r[\"host\"] == \"ltvolp-ap5009wv\" or r[\"host\"] == \"ltvolp-ap5010wv\" or r[\"host\"] == \"ltvolp-ap5011wv\" or r[\"host\"] == \"ltvolp-ap5012wv\")\r\n |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "NETWORK_MIN_SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 245 } },
  {
   "title": "MIN-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 246 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Received_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SQL-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 246 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Sent_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MIN-NETWORK-Bytes sent / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Sent_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SQL-NETWORK-Bytes sent / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Sent_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolm-ap50.*/)\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "NETWORK_CACHE_Report Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 262 } },
  {
   "title": "CACHE-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Received_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltibrb-we5002wv\" or r[\"host\"] == \"ltibrb-we5003wv\" or r[\"host\"] == \"ltibrb-we5004wv\" or r[\"host\"] == \"ltibrb-we5005wv\" or r[\"host\"] == \"ltibrb-we5006wv\")\r\n |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CACHE-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Received_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltibrb-we5002wv\" or r[\"host\"] == \"ltibrb-we5003wv\" or r[\"host\"] == \"ltibrb-we5004wv\" or r[\"host\"] == \"ltibrb-we5005wv\" or r[\"host\"] == \"ltibrb-we5006wv\")\r\n |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Report Service-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Received_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolr-rp50.*/)\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Report Service-NETWORK-Bytes sent / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Sent_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvolr-rp50.*/)\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "NETWORK_FinstreamAdapter_RsAccess",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 279 }
  },
  {
   "title": "FinstreamAdapter-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Received_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvola-ap50.*/)\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "FinstreamAdapter-NETWORK-Bytes sent / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 280 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Sent_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /ltvola-ap50.*/)\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RsAccess-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Received_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5001wv\" or r[\"host\"] == \"ltvolt-ap5002wv\" or r[\"host\"] == \"ltvolt-ap5003wv\" or r[\"host\"] == \"ltvolt-ap5004wv\" or r[\"host\"] == \"ltvolt-ap5005wv\" or r[\"host\"] == \"ltvolt-ap5006wv\" or r[\"host\"] == \"ltvolt-ap5007wv\" or r[\"host\"] == \"ltvolt-ap5008wv\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RsAccess-NETWORK-Bytes sent / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 288 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Sent_persec\")\r\n |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5001wv\" or r[\"host\"] == \"ltvolt-ap5002wv\" or r[\"host\"] == \"ltvolt-ap5003wv\" or r[\"host\"] == \"ltvolt-ap5004wv\" or r[\"host\"] == \"ltvolt-ap5005wv\" or r[\"host\"] == \"ltvolt-ap5006wv\" or r[\"host\"] == \"ltvolt-ap5007wv\" or r[\"host\"] == \"ltvolt-ap5008wv\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "NETWORK_TelebankCommands_MTE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 296 } },
  {
   "title": "TelebankCommands-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Received_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5009wv\" or r[\"host\"] == \"ltvolt-ap5010wv\" or r[\"host\"] == \"ltvolt-ap5011wv\" or r[\"host\"] == \"ltvolt-ap5012wv\" or r[\"host\"] == \"ltvolt-ap5013wv\" or r[\"host\"] == \"ltvolt-ap5014wv\" or r[\"host\"] == \"ltvolt-ap5015wv\" or r[\"host\"] == \"ltvolt-ap5016wv\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TelebankCommands-NETWORK-Bytes sent / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Sent_persec\")\r\n |> filter(fn: (r) => r[\"host\"] == \"ltvolt-ap5009wv\" or r[\"host\"] == \"ltvolt-ap5010wv\" or r[\"host\"] == \"ltvolt-ap5011wv\" or r[\"host\"] == \"ltvolt-ap5012wv\" or r[\"host\"] == \"ltvolt-ap5013wv\" or r[\"host\"] == \"ltvolt-ap5014wv\" or r[\"host\"] == \"ltvolt-ap5015wv\" or r[\"host\"] == \"ltvolt-ap5016wv\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MTE-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Received_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5001wv\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MTE-NETWORK-Bytes sent / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Sent_persec\")\r\n |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5001wv\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "NETWORK_ProcessClusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 313 } },
  {
   "title": "ProcessClusters-NETWORK-Bytes received / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 314 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Received_persec\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5007wv\" or r[\"host\"] == \"ltvolp-ap5008wv\" or r[\"host\"] == \"ltvolp-ap5009wv\" or r[\"host\"] == \"ltvolp-ap5010wv\" or r[\"host\"] == \"ltvolp-ap5011wv\" or r[\"host\"] == \"ltvolp-ap5012wv\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ProcessClusters-NETWORK-Bytes sent / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 314 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"vtb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bytes_Sent_persec\")\r\n |> filter(fn: (r) => r[\"host\"] == \"ltvolp-ap5007wv\" or r[\"host\"] == \"ltvolp-ap5008wv\" or r[\"host\"] == \"ltvolp-ap5009wv\" or r[\"host\"] == \"ltvolp-ap5010wv\" or r[\"host\"] == \"ltvolp-ap5011wv\" or r[\"host\"] == \"ltvolp-ap5012wv\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}