{
 "title": "JVM v2",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "kubernetes_namespace",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\"}, kubernetes_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{kubernetes_name=~\"$name\"}, instance)"
    }
   },
   {
    "name": "thread_states",
    "query": {
     "query": "label_values(jvm_threads_states_threads, state)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=~\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=~\"$instance\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "type",
    "query": "name, app, kubernetes_name, application"
   },
   {
    "name": "hikari_pool",
    "query": {
     "query": "label_values(hikaricp_connections{kubernetes_namespace=~\"$kubernetes_namespace\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100*system_cpu_usage{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}",
       "legendFormat": "{{$type}} - {{instance}} - system"
      },
      {
       "expr": "100*process_cpu_usage{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}",
       "legendFormat": "{{$type}} - {{instance}} - process"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"heap\"}) by (kubernetes_name, instance)/sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"heap\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - usage %"
      }
     ]
    },
    {
     "title": "NonHeap Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"nonheap\"}) by (kubernetes_name, instance)/sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"nonheap\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - usage %"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads live",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live_threads{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}",
       "legendFormat": "{{$type}} - {{instance}} - live"
      }
     ]
    },
    {
     "title": "Threads daemon",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}",
       "legendFormat": "{{$type}} - {{instance}} - daemon"
      }
     ]
    },
    {
     "title": "Threads peak",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_peak_threads{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}",
       "legendFormat": "{{$type}} - {{instance}} - peak"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread States -  $thread_states",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "repeat": "thread_states",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", state=~\"$thread_states\"}",
       "legendFormat": "{{$type}} - {{instance}} - {{state}}"
      }
     ]
    },
    {
     "title": "Thread States -  $thread_states",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", state=~\"$thread_states\"}",
       "legendFormat": "{{$type}} - {{instance}} - {{state}}"
      }
     ]
    },
    {
     "title": "Thread States -  $thread_states",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", state=~\"$thread_states\"}",
       "legendFormat": "{{$type}} - {{instance}} - {{state}}"
      }
     ]
    },
    {
     "title": "Thread States -  $thread_states",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", state=~\"$thread_states\"}",
       "legendFormat": "{{$type}} - {{instance}} - {{state}}"
      }
     ]
    },
    {
     "title": "Thread States -  $thread_states",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", state=~\"$thread_states\"}",
       "legendFormat": "{{$type}} - {{instance}} - {{state}}"
      }
     ]
    },
    {
     "title": "Thread States -  $thread_states",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", state=~\"$thread_states\"}",
       "legendFormat": "{{$type}} - {{instance}} - {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"heap\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"heap\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"heap\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    },
    {
     "title": "JVM NonHeap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"nonheap\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"nonheap\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", area=\"nonheap\"}) by (kubernetes_name, instance)",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{$type}} - {{instance}} - commited"
      },
      {
       "expr": "jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{$type}} - {{instance}} - commited"
      },
      {
       "expr": "jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{$type}} - {{instance}} - commited"
      },
      {
       "expr": "jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    }
   ]
  },
  {
   "title": "NonHeap Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - commited"
      },
      {
       "expr": "jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - commited"
      },
      {
       "expr": "jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - commited"
      },
      {
       "expr": "jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - commited"
      },
      {
       "expr": "jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - commited"
      },
      {
       "expr": "jvm_memory_max_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{$type}} - {{instance}} - max"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers, bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=\"direct\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=\"direct\"}",
       "legendFormat": "{{$type}} - {{instance}} - capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers, count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=\"direct\"}",
       "legendFormat": "{{$type}} - {{instance}} - count"
      }
     ]
    },
    {
     "title": "Mapped Buffers, bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=\"mapped\"}",
       "legendFormat": "{{$type}} - {{instance}} - used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=\"mapped\"}",
       "legendFormat": "{{$type}} - {{instance}} - capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers, count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", id=\"mapped\"}",
       "legendFormat": "{{$type}} - {{instance}} - count"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}[3m])",
       "legendFormat": "{{$type}} - {{instance}} - {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{$type}} - {{instance}} - avg {{action}} ({{cause}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Http",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests To Service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}[5m])) by (method,status,uri,kubernetes_name)",
       "legendFormat": "{{method}} {{$type}} - {{uri}} -   [{{status}}] "
      }
     ]
    },
    {
     "title": "Response Time To Service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_sum{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", exception=\"None\"}[5m]))  by (method,status,uri,kubernetes_name) / sum(irate(http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", exception=\"None\"}[5m])) by (method,status,uri,kubernetes_name)",
       "legendFormat": "{{method}} {{$type}} - {{uri}} -   [{{status}}] "
      }
     ]
    },
    {
     "title": "Requests From Service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_client_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}[5m])) by (method,status,uri,kubernetes_name, clientName)",
       "legendFormat": "{{method}} - {{$type}} -> {{clientName}}{{uri}} -   [{{status}}] "
      }
     ]
    },
    {
     "title": "Response Time From Serive",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_client_requests_seconds_sum{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", uri!~\".*actuator.*\"}[5m])) by (method,status,uri,kubernetes_name, clientName) / sum(irate(http_client_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\", uri!~\".*actuator.*\"}[5m])) by (method,status,uri,kubernetes_name, clientName)",
       "legendFormat": "{{method}} - {{$type}} -> {{clientName}}{{uri}} -   [{{status}}] "
      }
     ]
    }
   ]
  },
  {
   "title": "Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Open Files",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "process_files_open_files{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\"}",
       "legendFormat": "Open Files - {{$type}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Stats (Optional)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "log4j2 Events",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(log4j2_events_total{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", level!=\"info\"}) by (kubernetes_name, level)",
       "legendFormat": "{{$type}} - {{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HikariCP (Optional)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_idle{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\",  pool=~\"$hikari_pool\"}",
       "legendFormat": "{{$type}} - {{instance}} - idle"
      },
      {
       "expr": "hikaricp_connections_active{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\",  pool=~\"$hikari_pool\"}",
       "legendFormat": "{{$type}} - {{instance}} - active"
      },
      {
       "expr": "hikaricp_connections_pending{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\",  pool=~\"$hikari_pool\"}",
       "legendFormat": "{{$type}} - {{instance}} - pending"
      }
     ]
    },
    {
     "title": "Creation Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(hikaricp_connections_creation_seconds_sum{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\",  pool=~\"$hikari_pool\"}[3m]) / irate(hikaricp_connections_creation_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\",  pool=~\"$hikari_pool\"}[3m])",
       "legendFormat": "{{$type}} - {{instance}} - Creation Time"
      }
     ]
    },
    {
     "title": "Usage Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(hikaricp_connections_usage_seconds_sum{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\",  pool=~\"$hikari_pool\"}[3m]) / irate(hikaricp_connections_usage_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\",  pool=~\"$hikari_pool\"}[3m])",
       "legendFormat": "{{$type}} - {{instance}} - Usage Time"
      }
     ]
    },
    {
     "title": "Acquire Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(hikaricp_connections_acquire_seconds_sum{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\",  pool=~\"$hikari_pool\"}[3m]) / irate(hikaricp_connections_acquire_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\", $type=~\"$name\", instance=~\"$instance\",  pool=~\"$hikari_pool\"}[3m])",
       "legendFormat": "{{$type}} - {{instance}} - Acquire Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka (Optional)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_request_total{kubernetes_namespace=~\"$kubernetes_namespace\"}[3m])) by ($type)",
       "legendFormat": "{{$type}} rate"
      }
     ]
    },
    {
     "title": "Consumer rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_request_total{kubernetes_namespace=~\"$kubernetes_namespace\"}[3m])) by ($type)",
       "legendFormat": "{{$type}} rate {{topic}}"
      }
     ]
    },
    {
     "title": "Producer sent, messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_producer_topic_record_send_total{kubernetes_namespace=~\"$kubernetes_namespace\"}[5m])) by ($type,topic)",
       "legendFormat": "[{{$type}}] produce [{{topic}}]"
      },
      {
       "expr": "sum(irate(kafka_producer_topic_record_send_total{kubernetes_namespace=~\"$kubernetes_namespace\"}[5m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Consumer read, messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_consumer_fetch_manager_records_consumed_total{kubernetes_namespace=~\"$kubernetes_namespace\", topic!~\"\"}[5m])) by ($type,topic)",
       "legendFormat": "[{{$type}}] consume [{{topic}}]"
      },
      {
       "expr": "sum(irate(kafka_consumer_fetch_manager_records_consumed_total{kubernetes_namespace=~\"$kubernetes_namespace\"}[5m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Producer sent, bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_producer_topic_byte_total{kubernetes_namespace=~\"$kubernetes_namespace\", topic!~\"\"}[3m])) by ($type, topic)",
       "legendFormat": "[{{$type}}] produce [{{topic}}]"
      },
      {
       "expr": "sum(irate(kafka_producer_topic_byte_total{kubernetes_namespace=~\"$kubernetes_namespace\"}[3m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Consumer read, bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_consumer_fetch_manager_bytes_consumed_total{kubernetes_namespace=~\"$kubernetes_namespace\",topic!~\"\"}[5m])) by ($type, topic)",
       "legendFormat": "[{{$type}}] consume [{{topic}}]"
      },
      {
       "expr": "sum(irate(kafka_consumer_fetch_manager_bytes_consumed_total{kubernetes_namespace=~\"$kubernetes_namespace\"}[5m]))",
       "legendFormat": "SUM"
      }
     ]
    }
   ]
  },
  {
   "title": "TomCat (Optional)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limit connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_connections_config_max_connections{kubernetes_namespace=~\"$kubernetes_namespace\"}) by ($type)/ count(tomcat_connections_config_max_connections{kubernetes_namespace=~\"$kubernetes_namespace\"}) by ($type)",
       "legendFormat": "{{$type}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_connections_current_connections{kubernetes_namespace=~\"$kubernetes_namespace\"}) by (kubernetes_pod)",
       "legendFormat": "{{kubernetes_pod}}"
      }
     ]
    },
    {
     "title": "Keep-alive connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_connections_keepalive_current_connections{kubernetes_namespace=~\"$kubernetes_namespace\"}) by (kubernetes_pod)",
       "legendFormat": "{{kubernetes_pod}}"
      }
     ]
    },
    {
     "title": "Limit threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_threads_config_max_threads{kubernetes_namespace=~\"$kubernetes_namespace\"}) by ($type)/ count(tomcat_threads_config_max_threads{kubernetes_namespace=~\"$kubernetes_namespace\"}) by ($type)",
       "legendFormat": "{{$type}}"
      }
     ]
    },
    {
     "title": "Current threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_threads_current_threads{kubernetes_namespace=~\"$kubernetes_namespace\"}) by (kubernetes_pod)",
       "legendFormat": "{{kubernetes_pod}}"
      }
     ]
    },
    {
     "title": "Busy threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_threads_busy_threads{kubernetes_namespace=~\"$kubernetes_namespace\"}) by (kubernetes_pod)",
       "legendFormat": "{{kubernetes_pod}}"
      }
     ]
    },
    {
     "title": "TomCat errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(tomcat_global_error_total{kubernetes_namespace=~\"$kubernetes_namespace\"}[5m])) by (kubernetes_pod)",
       "legendFormat": "{{$kubernetes_pod}}"
      }
     ]
    },
    {
     "title": "Requests, rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(tomcat_global_request_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\"}[5m])) by ($type)",
       "legendFormat": "{{$type}}"
      }
     ]
    }
   ]
  }
 ]
}