{
 "title": "Exa Advanced k6 Dashboard",
 "description": "An advanced dashboard for visualizing results from the k6.io load testing tool, using the InfluxDB exporter to track and watch requests with their status codes and latencies.",
 "time": { "from": "2021-10-05T09:49:38.153Z", "to": "2021-10-05T10:24:03.663Z" },
 "templating": {
  "list": [
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_looking_up,http_req_receiving,http_req_sending,http_req_waiting"
   }
  ]
 },
 "panels": [
  { "title": "Checks and Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Annotated Tests", "type": "annolist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  {
   "title": "Checks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"checks\" WHERE $timeFilter  GROUP BY \"check\", \"group\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests Success and Failure Stats",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "endpoint" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "checks",
     "query": "SELECT sum(\"value\") as \"Success Count\", count(\"value\") as Total FROM \"checks\" WHERE $timeFilter GROUP BY \"endpoint\", \"group\", \"status\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Request Latency",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT percentile(\"value\", 95), percentile(\"value\", 99), max(\"value\"), median(\"value\"), stddev(\"value\") FROM /^$Measurement$/ WHERE (\"status\" = '202' OR \"status\" = '200' OR \"status\" = '204') AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "202" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "200" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "204" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "check" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$Measurement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "Measurement" },
  {
   "title": "$Measurement (mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM $Measurement WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM $Measurement WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (med)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"value\") FROM $Measurement WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"value\") FROM $Measurement WHERE $timeFilter and value > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (p90)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"value\", 90) FROM $Measurement WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (p95)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"value\", 95) FROM $Measurement WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "graph",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT max(\"value\") FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT percentile(\"value\", 95) FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "p90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT percentile(\"value\", 90) FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT min(\"value\") FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT \"value\" FROM $Measurement WHERE $timeFilter and value > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}