{
 "title": "k6 Load Testing Results (Prometheus)",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the Prometheus.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "label": "scenario",
    "query": {
     "query": "label_values(k6_iterations, scenario)"
    }
   },
   {
    "name": "domain",
    "label": "domain",
    "query": {
     "query": "label_values(k6_http_reqs, url)"
    }
   },
   {
    "name": "HttpMetricName",
    "label": "HttpMetricName",
    "query": "blocked,connecting,duration,receiving,sending,tls_handshaking,waiting"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "VUs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "Virtual Users" },
    { "expr": "k6_vus_max", "legendFormat": "Max Users" }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs{scenario=\"$scenario\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Iterations per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_iterations[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_received[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(k6_data_sent[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (k6_http_reqs{scenario=\"${scenario}\", url=~\".*${domain}.*\"})",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Status code (${domain})",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(k6_http_reqs{scenario=\"${scenario}\", url=~\".*${domain}.*\"}) by (status, method)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response time ${HttpMetricName} (avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_${HttpMetricName}_avg{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "P95 (avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_${HttpMetricName}_p95{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "max (${HttpMetricName})",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_${HttpMetricName}_max{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "min (${HttpMetricName})",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_${HttpMetricName}_min{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "K6 latency (${HttpMetricName})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(k6_http_req_${HttpMetricName}_p95{scenario=\"${scenario}\", url=~\".*${domain}.*\"}) ",
     "legendFormat": "P95"
    },
    {
     "expr": "avg(k6_http_req_${HttpMetricName}_p90{scenario=\"${scenario}\", url=~\".*${domain}.*\"})",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Query (${domain})",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(k6_http_reqs{scenario=\"${scenario}\", url=~\".*${domain}.*\"}) by (url, status)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}