{
 "title": "K6_Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "k6_http_reqs_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_reqs_total" }
   ]
  },
  {
   "title": "k6_http_req_failed_rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_req_failed_rate" }
   ]
  },
  {
   "title": "k6_data_received_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_data_received_total\r" }
   ]
  },
  {
   "title": "k6_http_req_receiving_p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_req_receiving_p99" }
   ]
  },
  {
   "title": "k6_iterations_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_iterations_total" }
   ]
  },
  {
   "title": "k6_http_req_sending_p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_req_sending_p99" }
   ]
  },
  {
   "title": "k6_iteration_duration_p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_iteration_duration_p99" }
   ]
  },
  {
   "title": "k6_http_req_tls_handshaking_p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "k6_http_req_tls_handshaking_p99"
    }
   ]
  },
  {
   "title": "k6_http_reqs_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_reqs_total" }
   ]
  },
  {
   "title": "k6_http_req_waiting_p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_req_waiting_p99" }
   ]
  },
  {
   "title": "k6_http_req_connecting_p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_req_connecting_p99" }
   ]
  },
  {
   "title": "k6_http_req_duration_p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_req_duration_p99" }
   ]
  },
  {
   "title": "k6_http_req_blocked_p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_req_blocked_p99" }
   ]
  },
  {
   "title": "k6_data_sent_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_data_sent_total" }
   ]
  },
  {
   "title": "k6_data_received_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_data_received_total" }
   ]
  }
 ]
}