{
 "title": "Kafka Template V1.1",
 "description": "V1",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount{ris_code=\"$ris_code\"}, kubernetes_namespace)"
    }
   },
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount{ris_code=~\"$ris_code\"},cluster_name)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values({ris_code=\"$ris_code\", cluster_name=~\"$cluster_name\"},topic)"
    }
   },
   { "name": "ris_code", "label": "ris_code", "query": "1041" },
   { "name": "CPU", "label": "CPU", "query": "4" },
   {
    "name": "instance_wo_port",
    "label": "Kafka hosts",
    "query": {
     "query": "label_values({cluster_name=~\"$cluster_name\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "KAFKA KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Инфраструктура кластера",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance_wo_port.*\"})"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance_wo_port.*\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance_wo_port.*\", mountpoint=\"/app\"}"
    }
   ]
  },
  {
   "title": "Статус кластера",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{instance=~\"$instance_wo_port.*\"}) by (instance)"
    },
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{cluster_name=~\"$cluster_name\"} > 0"
    },
    {
     "expr": "up{instance=~\"$instance_wo_port.*\", metrics_path=\"/app\"}"
    }
   ]
  },
  {
   "title": "Утилизация раздела диска раздела /app на данный момент",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{mountpoint=\"/app\", instance=~\"$instance_wo_port.*\"} - node_filesystem_free_bytes{mountpoint=\"/app\", instance=~\"$instance_wo_port.*\"}) / node_filesystem_size_bytes{mountpoint=\"/app\", instance=~\"$instance_wo_port.*\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Свободное место диска раздела /app",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/app\", instance=~\"$instance_wo_port.*\"}",
     "legendFormat": "{{instance}}{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Общая информация по кластеру Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Доступность узлов",
     "type": "graph",
     "description": "Количество работающих брокеров в кластере.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{instance=~\"$instance_wo_port.*\", metrics_path=\"/app\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(up{instance=~\"$instance_wo_port.*\", metrics_path=\"/app\"})",
       "legendFormat": "TOTAL brokers up"
      }
     ]
    },
    {
     "title": "Количество активных контроллеров кластера",
     "type": "graph",
     "description": "Количество активных контроллеров кластера.\nДолжно быть строго равно 1",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_activecontrollercount{cluster_name=~\"$cluster_name\"} > 0",
       "legendFormat": "Controller: {{ci_host}}"
      }
     ]
    },
    {
     "title": "Количество ведущих партиций, не имеющих достаточное количество синхронизированных реплик",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_replicamanager_underreplicatedpartitions{cluster_name=~\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Максимальное отставание реплики от ведущего раздела",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_replicafetchermanager_maxlag{clientId=\"Replica\", cluster_name=~\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Количество партиций на брокере",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_replicamanager_partitioncount{cluster_name=~\"$cluster_name\"}",
       "legendFormat": "{{ci_host}}"
      }
     ]
    },
    {
     "title": "Количество групп потребителей (consumer group count)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_consumergroup_group_count{cluster_name=~\"$cluster_name\"}) by (ci_host)",
       "legendFormat": "{{ci_host}}"
      }
     ]
    },
    {
     "title": "Количество Leader партиций на брокере",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_replicamanager_leadercount{cluster_name=~\"$cluster_name\"}",
       "legendFormat": "{{ci_host}}"
      }
     ]
    },
    {
     "title": "Количество партиций с числом реплик меньше minISR",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_replicamanager_underminisrpartitioncount{cluster_name=~\"$cluster_name\"}",
       "legendFormat": "{{ci_host}}"
      }
     ]
    }
   ]
  },
  { "title": "LAG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Kafka LAG by topic (avg)",
   "type": "graph",
   "description": "Указывается накапливающийся ЛАГ в указанном кластере по топику.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(kafka_consumergroup_group_topic_lag{cluster_name=~\"$cluster_name\", topic=~\"$topic\", topic!=\"\"}) by (instance, topic, group)) by (topic, group)",
     "legendFormat": "{{topic}} - {{group}}"
    }
   ]
  },
  {
   "title": "Kafka LAG by topic (max)",
   "type": "graph",
   "description": "Указывается накапливающийся ЛАГ в указанном кластере по топику.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kafka_consumergroup_group_topic_lag{cluster_name=~\"$cluster_name\", topic=~\"$topic\", topic!=\"\"}) by (instance, topic, group)) by (topic, group)",
     "legendFormat": "{{topic}} - {{group}}"
    }
   ]
  },
  {
   "title": "Kafka LAG by (topic, instance)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_topic_lag{cluster_name=~\"$cluster_name\", topic=~\"$topic\"}) by (topic, instance)",
     "legendFormat": "{{topic}}: {{instance}}"
    }
   ]
  },
  { "title": "CPU & RAM & DISK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Загрузка CPU Kafka (NODE EXPORTER)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$instance_wo_port.*\"}[5m])) / $CPU * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Загрузка CPU Kafka (kafka exporter)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(process_cpu_seconds_total{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port:7171\"}[5m])) / $CPU * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Утилизация раздела /app брокеров Kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{mountpoint=\"/app\", instance=~\"$instance_wo_port.*\"} - node_filesystem_free_bytes{mountpoint=\"/app\", instance=~\"$instance_wo_port.*\"}) / node_filesystem_size_bytes{mountpoint=\"/app\", instance=~\"$instance_wo_port.*\"}) * 100",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Свободное место в разделе /app брокера Kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/app\", instance=~\"$instance_wo_port.*\"}",
     "legendFormat": "{{instance}}{{mountpoint}}"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance_wo_port.*\"} / (node_memory_MemTotal_bytes{instance=~\"$instance_wo_port.*\"}))) * 100",
     "legendFormat": "{{instance}} RAM used"
    }
   ]
  },
  {
   "title": "RAM Cashed",
   "type": "graph",
   "description": "При нормальной работе кластера Кафки на высоких нагрузках кешируется практически вся память",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_Cached_bytes{instance=~\"$instance_wo_port.*\"}) / node_memory_MemTotal_bytes{instance=~\"$instance_wo_port.*\"} * 100",
     "legendFormat": "{{instance}} Cached RAM"
    }
   ]
  },
  {
   "title": "GC Collection time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port.*\"}[5m])",
     "legendFormat": "{{instance}} : {{gc}}"
    }
   ]
  },
  {
   "title": "GC Collection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port.*\"}[5m])",
     "legendFormat": "{{instance}} : {{gc}}"
    }
   ]
  },
  {
   "title": "Утилизация JVM HEAP KAFKA",
   "type": "graph",
   "description": "Показывается усредненная утилизация HEAP'а сервера кафки.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time(jvm_memory_bytes_used{area=\"heap\", ris_code=~\"$ris_code\", instance=~\"$instance_wo_port:7171\"}[5m])) by (area, instance) / sum (jvm_memory_bytes_max{area=\"heap\", ris_code=~\"$ris_code\", instance=~\"$instance_wo_port:7171\"}) by (area, instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} written"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} read"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} write"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} read time"
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} write time"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{ris_code=~\"$ris_code\", instance=~\"$instance_wo_port.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} - IO time"
    }
   ]
  },
  {
   "title": "Количество открытых файловых дескрипторов процессом Kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance_wo_port:7171\"} ",
     "legendFormat": "{{instance}}{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Количество выделенных файловых дескрипторов на хосте",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance_wo_port.*\"} ",
     "legendFormat": "{{instance}}{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Сетевые интерфейсы работы с клиентами",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 }
  },
  {
   "title": "Средний размер входящего сообщения ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{ris_code=~\"$ris_code\", topic=~\"$topic\" ,topic!=\"__consumer_offsets\", topic!=\"\"}[1m])) by (topic)/ sum(rate(kafka_server_brokertopicmetrics_messagesin_total{ris_code=~\"$ris_code\", topic=~\"$topic\", topic!=\"__consumer_offsets\", topic!=\"\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Количество входящих сообщений по брокерам, штук / сек",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[5m]))",
     "legendFormat": "TOTAL Messages IN"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Количество входящих сообщений по топикам, штук / сек",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{ris_code=~\"$ris_code\", topic=~\"$topic\", topic!=\"__consumer_offsets\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{ris_code=~\"$ris_code\", topic=~\"$topic\", topic!=\"__consumer_offsets\"}[5m]))",
     "legendFormat": "TOTAL messagen IN"
    }
   ]
  },
  {
   "title": "Объем записываемых клиентами данных (producer по instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[5m]))",
     "legendFormat": "TOTAL bytes IN"
    }
   ]
  },
  {
   "title": "Объем считываемых данных клиентами (consumer по instance)",
   "type": "graph",
   "description": "Объем считываемых данных клиентами (consumer)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[5m]))",
     "legendFormat": "TOTAL bytes OUT"
    }
   ]
  },
  {
   "title": "Среднее время бездействия обработчиков запросов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(rate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent{cluster_name=~\"$cluster_name\"}[5m]) / 1e09, 1) * 100",
     "legendFormat": "{{instance}} - requestHandlerIdlePerCent"
    }
   ]
  },
  {
   "title": "Фон ошибок (producer/consumer)\t",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_failedfetchrequests_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[1m]) / rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[1m]) * 100",
     "legendFormat": "{{instance}} - consumerError"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_failedproducerequests_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[1m]) / rate(kafka_server_brokertopicmetrics_totalproducerequests_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[1m]) * 100",
     "legendFormat": "{{instance}} - producerError"
    }
   ]
  },
  { "title": "Кластерные сетевые интерфейсы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 } },
  {
   "title": "Объем данных, получаемый от других брокеров",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_replicationbytesin_oneminuterate{cluster_name=~\"$cluster_name\"} or rate(kafka_server_brokertopicmetrics_replicationbytesin_total{cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{ci_host}}"
    }
   ]
  },
  {
   "title": "Объем данных, отправляемый другим брокерам",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_replicationbytesout_oneminuterate{cluster_name=~\"$cluster_name\"} or rate(kafka_server_brokertopicmetrics_replicationbytesout_total{cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{ci_host}}"
    }
   ]
  },
  {
   "title": "Кол-во API запросов к кластеру Kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (request) (rate(kafka_network_requestmetrics_requests_total{cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "События и исключительные ситуации",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (request, error)  (rate(kafka_network_requestmetrics_errors_total{error!=\"NONE\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "Request: {{request}} Error: {{error}}"
    }
   ]
  },
  {
   "title": "Объем данных репликации",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesin_total{ris_code=~\"$ris_code\", cluster_name=~\"$cluster_name\"}[5m])",
     "legendFormat": "{{instance}} - replicationBytesIn"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesout_total{ris_code=~\"$ris_code\", cluster_name=~\"$cluster_name\"}[5m])",
     "legendFormat": "{{instance}} - replicationBytesOut"
    }
   ]
  },
  {
   "title": "Длина очереди запросов / ответов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_requestqueuesize{ris_code=~\"$ris_code\", cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}} - requestQueueSize"
    },
    {
     "expr": "kafka_network_requestchannel_responsequeuesize{ris_code=~\"$ris_code\",  cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}} - responseQueueSize"
    }
   ]
  },
  {
   "title": "Разница между входящим и исходящим трафиком",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[5m])) - sum(rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"\",instance=~\"$instance_wo_port.*\"}[5m]))",
     "legendFormat": "IN - OUT"
    }
   ]
  },
  {
   "title": "Входящий трафик ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance_wo_port.*\"}[5m]) * 8) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Исходящий трафик ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$instance_wo_port.*\"}[5m]) * 8) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Количество установленных TCP соединений",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$instance_wo_port.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Среднее время бездействия обработчиков сетевого трафика",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_network_socketserver_networkprocessoravgidlepercent{cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Produser / Consumer openshift service rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer rate ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_request_total{kubernetes_namespace=~\"$namespace\"}[1m])) by (app)",
       "legendFormat": "{{app}} rate"
      }
     ]
    },
    {
     "title": "Consumer rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_request_total{kubernetes_namespace=~\"$namespace\"}[1m])) by (app)",
       "legendFormat": "{{app}} rate"
      }
     ]
    },
    {
     "title": "Producer sent, messages/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_topic_record_send_total{kubernetes_namespace=~\"$namespace\"}[1m])) by (app,topic)",
       "legendFormat": "[{{app}}] produce [{{topic}}]"
      },
      {
       "expr": "sum(rate(kafka_producer_topic_record_send_total{kubernetes_namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Consumer read, messages/sec ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_fetch_manager_records_consumed_total{kubernetes_namespace=~\"$namespace\", topic!~\"\"}[1m])) by (app,topic)",
       "legendFormat": "[{{app}}] consume [{{topic}}]"
      },
      {
       "expr": "sum(rate(kafka_consumer_fetch_manager_records_consumed_total{kubernetes_namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "TOTAL reads"
      }
     ]
    },
    {
     "title": "Producer sent, bytes/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_topic_byte_total{kubernetes_namespace=~\"$namespace\", topic!~\"\"}[1m])) by (app, topic)",
       "legendFormat": "[{{app}}] produce [{{topic}}]"
      },
      {
       "expr": "sum(rate(kafka_producer_topic_byte_total{kubernetes_namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Consumer read, bytes/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_fetch_manager_bytes_consumed_total{kubernetes_namespace=~\"$namespace\",topic!~\"\"}[1m])) by (app, topic)",
       "legendFormat": "[{{app}}] consume [{{topic}}]"
      },
      {
       "expr": "sum(rate(kafka_consumer_fetch_manager_bytes_consumed_total{kubernetes_namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Average execution time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(spring_kafka_listener_seconds_sum{ris_code=\"$ris_code\", kubernetes_namespace=~\"$namespace\"}[1m])) by (kubernetes_namespace, app)/sum(irate(spring_kafka_listener_seconds_count{ris_code=\"$ris_code\", kubernetes_namespace=~\"$namespace\"}[1m])) by (kubernetes_namespace, app) ",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  }
 ]
}