{
 "title": "MAIN INFO - MONITORING_2",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "DB_Instance",
    "query": "show tag values FROM \"win_cpu\" with key=host"
   },
   { "name": "Granularity", "query": "10s,30s,1m,3m,6m" },
   {
    "name": "app",
    "query": "VTB24.Minerva.Host.WinService,VTB24.FinstreamAdapter"
   }
  ]
 },
 "panels": [
  { "title": "Perfmon SQL Server Minerva DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Connections \\ Total Number Of Pulled Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQLServerGeneral",
     "select": [
      [
       { "params": [ "User_Connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User_Connections" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "alias": "sum minerva",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": ".Net_SqlServer",
     "query": "SELECT sum(\"NumberOfPooledConnections\") FROM \".Net_SqlServer\" WHERE $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "NumberOfPooledConnections" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MSSQL Latches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQLServerLatches",
     "query": "SELECT mean(\"Total_Latch_Wait_Time_(ms)\") AS \"Total_Latch_Wait_Time_(ms)\" FROM \"SQLServerLatches\" WHERE (\"host\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Total_Latch_Wait_Time_(ms)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total_Latch_Wait_Time_(ms)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Locks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQLServerLocks",
     "select": [
      [
       { "params": [ "Lock_Waits_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Lock_waits/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Database Replica",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQLServerDatabaseReplica",
     "select": [
      [
       { "params": [ "Database_Flow_Control_Delay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Lock_waits/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Memory Manager",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQLServerMemoryManager",
     "select": [
      [
       { "params": [ "Optimizer_Memory_(KB)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Optimizer_Memory (KB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Transactions / Handle Count / Thread Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQLServerGeneral",
     "select": [
      [
       { "params": [ "Transactions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Transactions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "select": [
      [
       { "params": [ "Thread_Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Thread_Count" ], "type": "alias" }
      ],
      [
       { "params": [ "Handle_Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Handle_Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "OR", "key": "instance", "operator": "=", "value": "sqlserv" }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Context_Switches / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "Context_Switches_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Context_Switches / sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Batch_Requests / sec, Compilations /sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQLServerStatistics",
     "select": [
      [
       { "params": [ "Batch_Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Batch_Requests / sec" ], "type": "alias" }
      ],
      [
       { "params": [ "SQL_Compilations_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Compilations / sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received / sec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent / sec\", mean(\"Bytes_Total_persec\") AS \"Bytes Total / sec\" FROM \"win_net\" WHERE (\"host\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Received / sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Sent / sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Total_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Total / sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL-Free space_disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_instance",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Free_Megabytes\") FROM \"win_disk\" WHERE \"host\" = 'K10-TBSQL-1' AND \"instance\" = '[a-z]*' AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "Free_Megabytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free_Magabytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/.*[A-Z]+:.*/" }
     ]
    }
   ]
  },
  {
   "title": "ReplicationInfo Time_Lag",
   "type": "graph",
   "description": "Run script to collect data",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name $tag_replica_instance_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "replica_instance_name" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ReplicationInfo_2019",
     "select": [
      [
       { "params": [ "Time_LAG" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Time_Lag" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "availability_group_name", "operator": "=", "value": "TBSQL9" },
      { "condition": "OR", "key": "database_name", "operator": "=", "value": "TBEmit001" },
      { "condition": "OR", "key": "database_name", "operator": "=", "value": "TBArchive" }
     ]
    }
   ]
  },
  {
   "title": "ReplicationInfo",
   "type": "graph",
   "description": "Run script to collect data",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name $tag_replica_instance_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "replica_instance_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ReplicationInfo",
     "query": "SELECT last(\"redo_queue_size\") AS \"redo_queue_size\", last(\"log_send_queue_size\") AS \"log_send_queue_size\" FROM \"ReplicationInfo_2019\" WHERE (\"availability_group_name\" = 'TBSQL9' OR \"database_name\" = 'TBEmit001' OR \"database_name\" = 'TBArchive') AND $timeFilter GROUP BY time($__interval), \"servername\", \"database_name\", \"replica_instance_name\" fill(linear)",
     "select": [
      [
       { "params": [ "redo_queue_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "redo_queue_size" ], "type": "alias" }
      ],
      [
       { "params": [ "log_send_queue_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "log_send_queue_size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "availability_group_name", "operator": "=", "value": "K10-TBSQL" },
      { "condition": "OR", "key": "database_name", "operator": "=", "value": "TBEmit001" },
      { "condition": "OR", "key": "database_name", "operator": "=", "value": "TBArchive" }
     ]
    }
   ]
  },
  {
   "title": "main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Minerva_L0_IdentitfiedSessions_TOTAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "IdentitfiedSessions",
       "query": "SELECT sum(\"IdentitfiedSessions\") AS \"IdentitfiedSessions\" FROM \"IdentitfiedSessions\" WHERE $timeFilter GROUP BY time(5s)",
       "select": [
        [
         { "params": [ "IdentitfiedSessions" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "IdentitfiedSessions" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "k10-tb-min-1" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-2" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-3" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-4" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-5" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-6" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-7" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-8" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-9" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-10" }
       ]
      }
     ]
    },
    {
     "title": "DB-CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      },
      {
       "alias": "$tag_host procInfo",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_proc_info",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of pooled connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": ".Net_SqlServer",
       "query": "SELECT mean(\"NumberOfPooledConnections\") FROM \".Net_SqlServer\" WHERE (\"host\" =~ /^K10-TB-MIN*/ AND \"objectname\" = '.NET Data Provider for SqlServer') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "NumberOfPooledConnections" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLM-AP.*/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/.*minerva.*/" }
       ]
      }
     ]
    },
    {
     "title": "Process Cluster Queue",
     "type": "graph",
     "description": "Run script to collect data",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_servername $tag_databasename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servername" ], "type": "tag" },
        { "params": [ "databasename" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "ProcessCluster",
       "select": [
        [
         { "params": [ "queueLength" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "MIN-CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLM-AP.*/" }
       ]
      }
     ]
    },
    {
     "title": "Minerva Exception thrown",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_dotnet_exceptions",
       "query": "SELECT mean(\"#_of_Exceps_Thrown_/_sec\") FROM \"win_dotnet_exceptions\" WHERE \"instance\" =~ /^$app$/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "#_of_Exceps_Thrown_/_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLM-AP.*/" },
        { "condition": "AND", "key": "instance", "operator": "=", "value": "VTB24.Minerva.Host.WinService" }
       ]
      }
     ]
    },
    {
     "title": "Avg. Fin. operations / min",
     "type": "graph",
     "description": "Run script to collect data",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_servername $tag_databasename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "servername" ], "type": "tag" },
        { "params": [ "databasename" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "FinOperations",
       "select": [
        [
         {
          "params": [
           "number_of_fin_operations_per_min"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "alias" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "OTHER-CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /.*L0VOLT-AP500[1-4].*/ OR \"host\" =~ /.*L0VOLP-AP500[1-4].*/ OR \"host\" =~ /.*L0IBRB-AP510[1-4].*/ OR \"host\" =~ /.*L0IBRB-AP500[1-4].*/ OR \"host\" =~ /.*L0VORL-AP500[1-2].*/ OR \"host\" =~ /.*L0VOLZ-AP500[1-9].*/ OR \"host\" =~ /.*L0VOLZ-AP50[10-22].*/ OR \"host\" =~ /*.L0VOLZ-DB5006.*/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLT-AP500[1-4].*/" },
        { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0VOLP-AP500[1-4].*/" },
        { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0IBRB-AP510[1-4].*/" },
        { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0IBRB-AP500[1-4].*/" },
        { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0VORL-AP500[1-2].*/" },
        { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP500[1-9].*/" },
        { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP50[10-22].*/" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "L0VOLZ-DB5006WV" }
       ]
      }
     ]
    },
    {
     "title": "Free space_disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "query": "SELECT mean(\"Free_Megabytes\") FROM \"win_disk\" WHERE (\"host\" =~ /.*/ AND \"instance\" =~ /.*[A-Z]+:.*/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" fill(none)",
       "select": [
        [
         { "params": [ "Free_Megabytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/.*[A-Z]+:.*/" }
       ]
      }
     ]
    },
    {
     "title": "Логинов в минуту, Распоряжений в минуту, % Распоряжний к логинам",
     "type": "gauge",
     "description": "Run script to collect data",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT GETDATE() AS time, count(1) AS LoginsPerMin FROM [TBEmit001].[dbo].[Sessions] (nolock) WHERE startTime between DATEADD(MINUTE, -1, GETDATE()) and GETDATE() ORDER BY 1"
      },
      {
       "rawSql": "SELECT GETDATE() AS time, count(1) AS FinOperationsPerMin  FROM [TBEmit001].[dbo].[Clusters] (nolock) WHERE CreateDate between DATEADD(MINUTE, -1, GETDATE()) and GETDATE() ORDER BY 1"
      },
      { "downsampler": "mean", "expression": "$C/$B*100", "type": "math", "upsampler": "fillna" }
     ]
    },
    {
     "title": "DB-Proc_time_Process",
     "type": "graph",
     "description": "count_Logical_CPU*100 = 16 000 предел",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_proc",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "DB-Numa Node Proc_time_Process",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_proc_info",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_proc_info\" WHERE (\"host\" = 'L0VOLD-DB5001WP' AND \"instance\" = '0,_Total') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "L0VOLD-DB5001WP" },
        { "condition": "AND", "key": "instance", "operator": "=", "value": "1,_Total" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_proc_info\" WHERE (\"host\" = 'L0VOLD-DB5001WP' AND \"instance\" = '1,_Total') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_proc_info\" WHERE (\"host\" = 'L0VOLD-DB5001WP' AND \"instance\" = '2,_Total') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_proc_info\" WHERE (\"host\" = 'L0VOLD-DB5001WP' AND \"instance\" = '3,_Total') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Текущее Количество УПИ",
     "type": "gauge",
     "description": "Run script to collect data",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT GETDATE() AS time, count(1) FROM dbo.OperationsInfoCache ORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "MINERVA-SESSIONS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "NEW_IdentitfiedSessions_TOTAL",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "IdentitfiedSessions",
       "query": "SELECT sum(\"IdentitfiedSessions\") AS \"IdentitfiedSessions\" FROM \"IdentitfiedSessions\" WHERE $timeFilter GROUP BY time(5s)",
       "select": [
        [
         { "params": [ "IdentitfiedSessions" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "IdentitfiedSessions" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "k10-tb-min-1" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-2" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-3" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-4" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-5" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-6" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-7" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-8" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-9" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-10" }
       ]
      }
     ]
    },
    {
     "title": "NEW_IdentitfiedSessions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "IdentitfiedSessions",
       "query": "SELECT mean(\"IdentitfiedSessions\") AS \"IdentitfiedSessions\" FROM \"IdentitfiedSessions\" WHERE $timeFilter GROUP BY time($__interval), host fill(null)",
       "select": [
        [
         { "params": [ "IdentitfiedSessions" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "IdentitfiedSessions" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "k10-tb-min-1" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-2" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-3" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-4" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-5" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-6" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-7" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-8" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-9" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-10" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MINERVA-SESSIONS_Clean_Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "NEW_CleanupCount",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "IdentitfiedSessions",
       "query": "SELECT mean(\"CleanupCount\") AS \"CleanupCount\" FROM \"IdentitfiedSessions\" WHERE $timeFilter GROUP BY time(1m), host",
       "select": [
        [
         { "params": [ "IdentitfiedSessions" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "IdentitfiedSessions" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "k10-tb-min-1" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-2" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-3" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-4" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-5" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-6" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-7" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-8" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-9" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-10" }
       ]
      }
     ]
    },
    {
     "title": "NEW_CleanedSessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "IdentitfiedSessions",
       "query": "SELECT mean(\"CleanedSessions\") AS \"CleanedSessions\" FROM \"IdentitfiedSessions\" WHERE $timeFilter GROUP BY time($__interval), host fill(null)",
       "select": [
        [
         { "params": [ "IdentitfiedSessions" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "IdentitfiedSessions" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "k10-tb-min-1" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-2" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-3" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-4" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-5" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-6" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-7" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-8" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-9" },
        { "condition": "OR", "key": "host", "operator": "=", "value": "k10-tb-min-10" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Min, Min_DB, Solo, App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "MIN-CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLM-AP.*/" }
       ]
      }
     ]
    },
    {
     "title": "SQL-CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "SOLO-CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLP-AP50.*/" }
       ]
      }
     ]
    },
    {
     "title": "APP-CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLT-AP50.*/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "CPU Pub, Cache, Callback, Ess", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "PUB-CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-PUB-.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0IBRB-AP51.*/" }
     ]
    }
   ]
  },
  {
   "title": " СИ-CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /.*L0VOLZ-AP50[12-22].*/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP50[12-22].*/" }
     ]
    }
   ]
  },
  {
   "title": "CACHE-CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0IBRB-AP50.*/" }
     ]
    }
   ]
  },
  {
   "title": "ExternalSystemsStub-CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /.*L0VOLZ-AP500[1-9]WV.*/ OR \"host\" =~ /.*L0VOLZ-AP50[10-12]WV.*/ OR \"host\" =~ /.*L0VOLZ-AP5001WV.*/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP500[1-9]WV.*/" },
      { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP50[10-11]WV.*/" }
     ]
    }
   ]
  },
  {
   "title": "Min_DB statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL-CPU % Priveleged Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Percent_Privileged_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "SQL-Process % Priveleged Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_proc",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Percent_Privileged_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "SQL-Process Thread Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_proc",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Thread_Count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "new_processes_blocked",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Processes blocked",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"Processes blocked | General Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Lock Wait Time (ms) Object",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"Lock Wait Time (ms) | Object | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Lock Wait Time (ms) Page",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"Lock Wait Time (ms) | Page | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Lock Waits/sec Object",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"Lock Waits/sec | Object | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Lock Waits/sec Page",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"Lock Waits/sec | Page | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SQLServerLocks",
       "select": [
        [
         { "params": [ "Lock_Wait_Time_(ms)" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Lock_Wait_Time (ms)" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Perfmon Wait Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_wait_statistics",
       "select": [
        [
         { "params": [ "Lock_waits" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Lock_waits" ], "type": "alias" }
        ],
        [
         { "params": [ "Page_latch_waits" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Page_latch_waits" ], "type": "alias" }
        ],
        [
         { "params": [ "Network_IO_waits" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Network_IO_waits" ], "type": "alias" }
        ],
        [
         { "params": [ "Log_buffer_waits" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Log_buffer_waits" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Perfmon Locks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Number of Deadlocks/sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"Number of Deadlocks/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Lock Waits/sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"Lock Waits/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Latch Waits/sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"Latch Waits/sec | Latches\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Lock Timeouts/sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"Lock Timeouts/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SQLServerLocks",
       "select": [
        [
         { "params": [ "Lock_Waits_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Lock_Waits/sec" ], "type": "alias" }
        ],
        [
         { "params": [ "Lock_Timeouts_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Lock_Timeouts/sec" ], "type": "alias" }
        ],
        [
         { "params": [ "Lock_Waits_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Lock_Waits/sec" ], "type": "alias" }
        ],
        [
         { "params": [ "Number_of_Deadlocks_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Number_of_Deadlocks/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_wait_statistics",
       "select": [
        [
         { "params": [ "Page_latch_waits" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Page_latch_waits" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MIN statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "# of Exception throwns / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_dotnet_exceptions",
       "query": "SELECT mean(\"#_of_Exceps_Thrown_/_sec\") FROM \"win_dotnet_exceptions\" WHERE \"instance\" =~ /^$app$/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "#_of_Exceps_Thrown_/_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLM-AP.*/" }
       ]
      }
     ]
    },
    {
     "title": "Number of pooled connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": ".Net_SqlServer",
       "query": "SELECT mean(\"#_of_Exceps_Thrown_/_sec\") FROM \"win_dotnet_exceptions\" WHERE \"instance\" =~ /^$app$/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "NumberOfPooledConnections" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLM-AP.*/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Stub-IIS statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "PostRequest/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_websvc",
     "select": [
      [
       { "params": [ "Post_Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP500[1-9].*/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Default Web Site" }
     ]
    }
   ]
  },
  {
   "title": "Total PostRequest/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_websvc",
     "query": "SELECT sum(\"Post_Requests_persec\") FROM \"win_websvc\" WHERE \"host\" = 'K10-TB-PER-SQL1' OR \"host\" = 'K10-TB-PER-SQL3' OR \"host\" = 'K10-TB-PERF-SQL' AND $timeFilter GROUP BY time(10s), \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Post_Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP500[1-9].*/" }
     ]
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_websvc",
     "select": [
      [
       { "params": [ "Current_Connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP500[1-9].*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP50[10-11].*/" }
     ]
    }
   ]
  },
  {
   "title": "PoshRq_sec - host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_websvc",
     "select": [
      [
       { "params": [ "Post_Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP500[1-9].*/" },
      { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP50[10-11].*/" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory Min, Min_DB, Solo, App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "MIN-Available bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLM-AP.*/" }
       ]
      }
     ]
    },
    {
     "title": "SQL-Available bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "SOLO-Available bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLP-AP50.*/" }
       ]
      }
     ]
    },
    {
     "title": "APP-Available bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*L0VOLT-AP50.*/" },
        { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0VOLT-AP50.*/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Available Memory Pub, Cache, Callback. Ess",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }
  },
  {
   "title": "ExternalSystemsStubAvailable bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP500[1-9].*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP50[10-11].*/" }
     ]
    }
   ]
  },
  {
   "title": "CACHE-Available bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0IBRB-AP50.*/" }
     ]
    }
   ]
  },
  {
   "title": "STUB СИ-Available bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0VOLZ-AP50[12-22].*/" }
     ]
    }
   ]
  },
  {
   "title": "PUB-Available bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0IBRB-AP51.*/" }
     ]
    }
   ]
  },
  {
   "title": "CACHE-Committed Bytes in Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /.*K10-TB-SOLO.*/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "Percent_Committed_Bytes_in_Use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*L0IBRB-AP50.*/" }
     ]
    }
   ]
  },
  {
   "title": "PUB-Committed Bytes in Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Percent_Committed_Bytes_in_Use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "K10-PC-GENV-146" },
      { "condition": "OR", "key": "host", "operator": "=~", "value": "/.*L0IBRB-AP51.*/" }
     ]
    }
   ]
  },
  {
   "title": "Free space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free space_disk_C",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Free_Megabytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*/" },
        { "condition": "AND", "key": "instance", "operator": "=", "value": "C:" }
       ]
      }
     ]
    },
    {
     "title": "Free space_disk_D",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 73 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Free_Megabytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*/" },
        { "condition": "AND", "key": "instance", "operator": "=", "value": "D:" }
       ]
      }
     ]
    },
    {
     "title": "Free space_diskS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 73 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Free_Megabytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/.*/" },
        { "condition": "AND", "key": "instance", "operator": "=", "value": "S:" }
       ]
      }
     ]
    }
   ]
  }
 ]
}