{
 "title": "PostgreSQL Queries (WIP)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "job", "query": "postgres_pgss" },
   {
    "name": "hostname",
    "query": "label_values(pg_up{job=~\"$job\"},hostname)"
   },
   {
    "name": "datname",
    "query": "label_values(pg_stat_statements_total_time{hostname=~\"$hostname\",datname!~\"template.*\"},datname)"
   },
   { "name": "how_many", "query": "5,10,20,50,100" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU time",
   "type": "graph",
   "description": "Total time is compute time + IO time.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_total_time{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Average CPU time per call",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_total_time{}[$__rate_interval]) \n/ rate(pg_stat_statements_calls{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  { "title": "Blocks IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Shared blocks read",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_shared_blks_read{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Shared blocks written",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_shared_blks_written{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Local blocks read",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_local_blks_read{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Local blocks written",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_local_blks_written{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Temp blocks read",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_temp_blks_read{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Temp blocks written",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_temp_blks_written{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Cache hits and dirtied blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shared blocks cache hits",
     "type": "graph",
     "description": "Cache hit means that a read was avoided due to block being already loaded to cache.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_shared_blks_hit{datname=~\"$datname\",hostname=\"$hostname\"}[$__rate_interval])))",
       "legendFormat": "{{queryid}}"
      }
     ]
    },
    {
     "title": "Local blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_local_blks_hit{datname=~\"$datname\",hostname=\"$hostname\"}[$__rate_interval])))",
       "legendFormat": "{{queryid}}"
      }
     ]
    },
    {
     "title": "Shared blocks dirtied",
     "type": "graph",
     "description": "The number of blocks ___dirtied___ indicates the number of ___previously unmodified___ blocks that were changed by this query. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_shared_blks_dirtied{hostname=~\"$hostname\",datname=~\"$datname\"}[$__rate_interval])))",
       "legendFormat": "{{queryid}}"
      }
     ]
    },
    {
     "title": "Local blocks dirtied",
     "type": "graph",
     "description": "The number of blocks ___dirtied___ indicates the number of ___previously unmodified___ blocks that were changed by this query. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_local_blks_dirtied{hostname=~\"$hostname\",datname=~\"$datname\"}[$__rate_interval])))",
       "legendFormat": "{{queryid}}"
      }
     ]
    }
   ]
  },
  { "title": "Calls and rows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Number of calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_calls{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Number of rows retrieved or affected",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk($how_many,rate(pg_stat_statements_rows{}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  }
 ]
}