{
 "title": "PostegreSQL LP 1.2",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "hostname",
    "query": "label_values(pg_settings_shared_buffers_bytes,instance)"
   },
   {
    "name": "datname",
    "query": "label_values(pg_stat_activity_count{instance=~\".*$hostname.*\",datname!~\"template.*\"},datname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Fast glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions",
     "type": "graph",
     "description": "Количество зафиксированных транзакций в этой базе данных(commit) и количество транзакций в этой базе данных, для которых был выполнен откат транзакции(rollback)",
     "gridPos": { "h": 7, "w": 23, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(pg_stat_database_xact_commit{server=~\"$hostname.*\", datname=~\"$datname\"}[1m]))",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "sum(-(irate(pg_stat_database_xact_rollback{server=~\"$hostname.*\", datname=~\"$datname\"}[1m])))",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Backend states",
     "type": "graph",
     "description": "Состояние бэкэнд процессов постгре, где каждый процесс обрабатывает 1 соедениние и может находится в статусах(active, idle, idle in transaction, disabled, idle in transaction (aborted), fastpath function call\n\nПодробное описание по ссылке сверху",
     "gridPos": { "h": 7, "w": 23, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (pg_stat_activity_count{server=~\"$hostname.*\",datname=~\"$datname\"})",
       "legendFormat": "{{datname}} {{state}}"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "graph",
     "description": "Частота попаданий в кэш, должно стремиться к 100%",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{datname=~\"$datname\", server=~\"$hostname.*\"} / (pg_stat_database_blks_read{datname=~\"$datname\", server=~\"$hostname.*\"} + pg_stat_database_blks_hit{datname=~\"$datname\", server=~\"$hostname.*\"}) ",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "graph",
     "description": "Количество запросов, отменённых из-за конфликта с восстановлением в этой базе данных(conflicts) и Количество взаимных блокировок, зафиксированное в этой базе данных (deadlocks)\n\nбольшое количество deadlocks говорит нам о деградации и некорректной работе БД, требует последующего анализа и исправления блокировок",
     "gridPos": { "h": 7, "w": 12, "x": 11, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_conflicts{server=~\"$hostname.*\", datname=~\"$datname\"}[1m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "irate(pg_stat_database_deadlocks{server=~\"$hostname.*\", datname=~\"$datname\"}[1m])",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Host info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "singlestat",
     "description": "Версия Постгре",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "pg_static{server=~\"$hostname.*\"}",
       "legendFormat": "{{short_version}}"
      }
     ]
    },
    {
     "title": "Start Time",
     "type": "singlestat",
     "description": "Время старта сервера.",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 2 },
     "format": "dateTimeFromNow",
     "valueName": "avg",
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=~\"$hostname.*\"} * 1000"
      }
     ]
    },
    {
     "title": "Current fetch data",
     "type": "singlestat",
     "description": "Количество строк, извлеченное запросами.",
     "gridPos": { "h": 2, "w": 2, "x": 5, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", job=\"$job\"})"
      }
     ]
    },
    {
     "title": "Current update data",
     "type": "singlestat",
     "description": "Количество строк, измененное запросами",
     "gridPos": { "h": 2, "w": 2, "x": 7, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", job=\"$job\"})"
      }
     ]
    },
    {
     "title": "Current insert data",
     "type": "singlestat",
     "description": "Количество строк, вставленное запросами",
     "gridPos": { "h": 2, "w": 2, "x": 9, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted{job=\"$job\", datname=~\"$datname\"})"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "singlestat",
     "description": "Максимальный вес служебного файла\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равным 8192 байта для БД типа OLTP, для OLAP необходимо уточнить информацию в стандартах, по аннотации сверху Борда.",
     "gridPos": { "h": 2, "w": 3, "x": 11, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Min Wal Size",
     "type": "singlestat",
     "description": "Минимальный вес служебного файла\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равным 2048 байта для БД типа OLTP, для OLAP необходимо уточнить информацию в стандартах, по аннотации сверху Борда.",
     "gridPos": { "h": 2, "w": 3, "x": 14, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_min_wal_size_bytes{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Temp file limit",
     "type": "singlestat",
     "description": "Задаёт максимальный объём дискового пространства, который сможет использовать один процесс для временных файлов\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равным 5% от pg_data для БД типа OLTP, для OLAP необходимо уточнить информацию в стандартах, по аннотации сверху Борда.",
     "gridPos": { "h": 2, "w": 2, "x": 17, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_temp_file_limit_bytes{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Max parallel workers per gather",
     "type": "singlestat",
     "description": "Задаёт максимальное число рабочих процессов, которые могут запускаться одним узлом Gather или Gather Merge\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равным 0 для БД типа OLTP, для OLAP необходимо уточнить информацию в стандартах, по аннотации сверху Борда.",
     "gridPos": { "h": 2, "w": 3, "x": 19, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers_per_gather{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "singlestat",
     "description": "Максимальное число рабочих процессов для параллельных запросов\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равным 0 для БД типа OLTP, для OLAP необходимо уточнить информацию в стандартах, по аннотации сверху Борда.",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "singlestat",
     "description": "Количество памяти, используемой для кэширования\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равным 25% от RAM",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{instance=~\".*$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "singlestat",
     "description": "Количество памяти, доступной для кэширования\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равным 80% от RAM\n",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "singlestat",
     "description": "Количество памяти для служебных задач (вроде restore или vacuum)\n\nв соответствии со стандартом УТАРИ maintenance_work_mem должно быть размером в 64 МБ(2 097 152 байт)",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "singlestat",
     "description": "Количество памяти, используемой для сортировки\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равным ( RAM - shared_buffers - maintenance_work_mem ) \\ max_connections",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "singlestat",
     "description": "Стоимость чтения одной страницы с диска. (уменьшение делает сканирование по индексу предпочтительнее)\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равен 1.1",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Checkpoint Timeout(In seconds)",
     "type": "singlestat",
     "description": "Максимальное время между автоматическими контрольными точками в WAL\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равен 1.1\n\nГраницы заданы для БД типа OLTP, если у вас OLAP обратитесь к стандартами мониторинга УТАРИ",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_checkpoint_timeout_seconds{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "singlestat",
     "description": "Стоимость чтения одной страницы с диска.",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_seq_page_cost{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "singlestat",
     "description": "Максимальное число фоновых процессов\n\nВ соответствии со стандартом УТАРИ данный показатель должен быть равен минимум 8",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "singlestat",
     "description": "Максимум коннектов к БД",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_connections{server=~\"$hostname.*\"}"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "graph",
     "description": "Средняя загрузка CPU за 1 минуту",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_load1{instance=~\"$hostname.*\"}[1m])",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "graph",
     "description": "Суммарное использование оперативной памяти",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$hostname.*\"}",
       "legendFormat": "Total bytes"
      },
      {
       "expr": "rate(node_memory_MemFree_bytes{instance=~\"$hostname.*\"}[1m])",
       "legendFormat": "Free bytes"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"$hostname.*\"}",
       "legendFormat": "Open FD"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active connections",
     "type": "graph",
     "description": "Количество подключений к каждой из БД(значение получается из суммы бекендов каждого типа, разделение по типам см в графике Sessions states\n\nCurrent number of backends. PostgreSQL creates a backend for each connected client.",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_numbackends{server=~\"$hostname.*\", datname=~\"$datname\"}",
       "legendFormat": "{{datname}} "
      }
     ]
    },
    {
     "title": "Connections / Max DB connections",
     "type": "graph",
     "description": "кол-во подключений/лимит подключений",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(sum(pg_stat_database_numbackends{server=~\"$hostname.*\"}))",
       "legendFormat": "backends"
      },
      {
       "expr": "sum(pg_settings_max_connections{server=~\"$hostname.*\"})",
       "legendFormat": "connections limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active sessions",
     "type": "graph",
     "description": "Число активных процессов, выполняющих какой-то запрос, в каждой БД(в данном контексте активные = backend in state \"active)",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", server=~\"$hostname.*\", state=\"active\"} !=0",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Sessions states",
     "type": "graph",
     "description": "Число backend процессов БД, отсортированных по типу",
     "gridPos": { "h": 7, "w": 12, "x": 11, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", server=~\"$hostname.*\", state=~\"idle|idle in transaction|idle in transaction (aborted)|active|fastpath function call|disabled\"}",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rollbacks",
     "type": "graph",
     "description": "Число транзакций в базе, которые были откачены назад",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_rollback{server=~\"$hostname.*\", datname=~\"$datname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Rows inserted/updated/deleted",
     "type": "graph",
     "description": "Rate of rows(=tuples) inserted, updated and deleted by queries.",
     "gridPos": { "h": 9, "w": 8, "x": 7, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_tup_inserted{server=~\"$hostname.*\", datname=~\"$datname\"}[1m]))",
       "legendFormat": "inserted"
      },
      {
       "expr": "sum(rate(pg_stat_database_tup_updated{server=~\"$hostname.*\", datname=~\"$datname\"}[1m]))",
       "legendFormat": "updated"
      },
      {
       "expr": "sum(rate(pg_stat_database_tup_deleted{server=~\"$hostname.*\", datname=~\"$datname\"}[1m]))",
       "legendFormat": "deleted"
      }
     ]
    },
    {
     "title": "Rows fetched/returned",
     "type": "graph",
     "description": "количество прочитанных/отсканированных строк в БД(returned) и количество строк содержащих данные необходимые для выполнения запроса(fetched)",
     "gridPos": { "h": 9, "w": 8, "x": 15, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_tup_fetched{server=~\"$hostname.*\", datname=~\"$datname\"}[1m]))",
       "legendFormat": "fetched"
      },
      {
       "expr": "sum(rate(pg_stat_database_tup_returned{server=~\"$hostname.*\", datname=~\"$datname\"}[1m]))",
       "legendFormat": "returned"
      }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch data (SELECT)",
     "type": "graph",
     "description": "Объем памяти извлеченное запросами (select) из каждой БД",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", server=~\"$hostname.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "graph",
     "description": "Количество строк измененное запросами в каждой БД",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", server=~\"$hostname.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "graph",
     "description": "Количество строк удаленное запросами(delete) в каждой БД",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", server=~\"$hostname.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "graph",
     "description": "Количество строк возвращенное запросами(returned) в каждой БД",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", server=~\"$hostname.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "graph",
     "description": "Количество строк вставленное запросами(inserted) в каждой БД",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 63 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", server=~\"$hostname.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "graph",
     "description": "Общее время, которое было затрачено на этап обработки контрольной точки, в котором файлы записываются на диск, в миллисекундах",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 63 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{server=~\"$hostname.*\"}[1m])",
       "legendFormat": "write_time "
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{server=~\"$hostname.*\"}[1m])",
       "legendFormat": "sync_time"
      }
     ]
    },
    {
     "title": "Temp File (Bytes)",
     "type": "graph",
     "description": "Общий объём данных, записанных во временные файлы запросами в этой базе данных. Учитываются все временные файлы, вне зависимости от того, по какой причине они созданы и вне зависимости от значения log_temp_files.",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_temp_bytes{server=~\"$hostname.*\", datname=~\"$datname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "graph",
     "description": "Количество буферов, записанных самим серверным процессом(buffers_backend) и Количество выделенных буферов(buffers_alloc)",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_buffers_backend{server=~\"$hostname.*\"}[1m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_alloc{server=~\"$hostname.*\"}[1m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{server=~\"$hostname.*\"}[1m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{server=~\"$hostname.*\"}[1m])",
       "legendFormat": "buffers_checkpoint"
      }
     ]
    },
    {
     "title": "Bgwriter checkpoints",
     "type": "graph",
     "description": "Количество запрошенных контрольных точек, которые уже были выполнены(checkpoints_req) и Количество запланированных контрольных точек, которые уже были выполнены(checkpoints_timed)",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_checkpoints_req{server=~\"$hostname.*\"}[1m])",
       "legendFormat": "Requested checkpoints"
      },
      {
       "expr": "rate(pg_stat_bgwriter_checkpoints_timed{server=~\"$hostname.*\"}[1m])",
       "legendFormat": "Scheduled checkpoints"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks by table",
     "type": "graph",
     "description": "Суммарное число блокировок в БД",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_locks_count{datname=~\"$datname\", server=~\"$hostname.*\"} != 0",
       "legendFormat": "{{datname}},{{mode}}"
      }
     ]
    },
    {
     "title": "Locks by type",
     "type": "graph",
     "description": "Суммарное число блокировок, отсортированное по типу",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_locks_count{server=~\"$hostname.*\", datname=~\"$datname\"}",
       "legendFormat": "{{mode}}"
      }
     ]
    }
   ]
  }
 ]
}