{
 "title": "PostgreSQL Query Drill-Down (Designed for PMM)",
 "description": "PostgreSQL Query Drill-Down ",
 "time": { "from": "2022-01-25T12:20:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": "label_values(pg_up,hostname)" },
   {
    "name": "queryid",
    "label": "Query ID",
    "query": "label_values(pg_stat_statements_calls{hostname=\"$host\",datname!~\"template.*\"},queryid)"
   },
   {
    "name": "query",
    "label": "Query",
    "query": "label_values(pg_stat_statements_calls{queryid=\"$queryid\"},query)"
   },
   { "name": "source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Selected queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_statements_calls{hostname=\"$host\",queryid=~\"$queryid\"}"
    }
   ]
  },
  {
   "title": "Query $queryid",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "<font color=#5991A7><b><center>$query</center></b></font>"
   }
  },
  {
   "title": "Query Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls{hostname=\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) or \nirate(pg_stat_statements_calls{hostname=\"$host\",queryid=~\"$queryid\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_total_time{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) or\nirate(pg_stat_statements_total_time{hostname=~\"$host\",queryid=~\"$queryid\"}[5m])) by (datname, queryid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Query Time per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_total_time{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) / \n(rate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) > 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Retrieved or Affected  Rows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_rows{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rows Processed per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_rows{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Read",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_read{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Read per Call",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_read{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) * 8 / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Read",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_local_blks_read{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Read per Call",
   "type": "graph",
   "description": "Each shared block has fixed size, by default the size is 8KiB.\n\n- ___Shared blocks___ contain regular tables and indices.\n- ___Local blocks___ contain temporary tables and indices.\n- ___Temp blocks___ contain short-lived working data, such as e.g. sorts.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_local_blks_read{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) * 8 / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Written",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_written{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Written per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_written{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Written",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_local_blks_written{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Written per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_local_blks_written{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Dirtied",
   "type": "graph",
   "description": "The number of blocks ___dirtied___ indicates the number of ___previously unmodified___ blocks that were changed by this query. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_dirtied{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Dirtied per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_dirtied{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Dirtied",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_local_blks_dirtied{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Dirtied per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_local_blks_dirtied{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval]) / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Cache Hits",
   "type": "graph",
   "description": "Cache hit means that a read was avoided due to block being already loaded to cache.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_hit{hostname=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Cache Hits per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_hit{hostname=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Cache Hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_local_blks_hit{hostname=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Cache Hits per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_local_blks_hit{hostname=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp Blocks I/O",
   "type": "graph",
   "description": "Data written through shared buffers (tables, indexes, etc.)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_temp_blks_read{hostname=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}} - Read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(pg_stat_statements_temp_blks_written{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "legendFormat": "{{queryid}} - {{datname}} - Written"
    }
   ]
  },
  {
   "title": "Temp Blocks I/O per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_temp_blks_read{hostname=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{hostname=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}} - Read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_statements_temp_blks_written{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=\"~$queryid\"}[$interval])",
     "legendFormat": "{{queryid}} - {{datname}} - Written"
    }
   ]
  }
 ]
}