{
 "title": "Redis Dashboard for LT",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Redis info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "info"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\"}  / redis_memory_max_bytes{instance=~\"$instance\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=~\"$instance\"} [1m])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "hits {{instance}}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses {{instance}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "used {{instance}}"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"} ",
     "legendFormat": "max  {{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "user {{instance}}"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "sys {{instance}}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "expired {{instance}}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted {{instance}}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100*(redis_keyspace_hits_total{instance=~\"$instance\"})/(redis_keyspace_hits_total{instance=~\"$instance\"}+redis_keyspace_misses_total{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=~\"$instance\"} [1m]))",
     "legendFormat": "top5 {{ cmd }}"
    },
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=~\"$instance\"}[1m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }} duration"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=~\"$instance\"}[1m])) by (cmd) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance =~ \"$instance\"}[1m])) by (cmd)\n  /\nsum(irate(redis_commands_total{instance =~ \"$instance\"}[1m])) by (cmd)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slowlog length",
   "type": "graph",
   "description": "by default 10ms and 128 len",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_slowlog_length{instance=\"$instance\"}",
     "legendFormat": "len"
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$instance\"})",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(redis_blocked_clients{instance=~\"$instance\"})",
     "legendFormat": "Blocked"
    }
   ]
  }
 ]
}