{
 "title": "Tarantool dashboard",
 "description": "Dashboard for Tarantool application and database server monitoring, based on grafonnet library.",
 "tags": [ "tarantool" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Application",
    "query": {
     "query": "label_values(tnt_info_uptime, job)"
    }
   },
   {
    "name": "zone",
    "query": {
     "query": "label_values(tnt_info_uptime{job=\"$job\"}, ris_sub)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(tnt_info_uptime{job=\"$job\", ris_sub=~\"$zone\"}, alias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TDG custom metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GraphQL -- query rps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(tdg_graphql_query_time_count{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}} - {{operation_name}}"
      }
     ]
    },
    {
     "title": "GraphQL -- avg. query time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(tdg_graphql_query_time_sum{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])/rate(tdg_graphql_query_time_count{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}} - {{operation_name}}"
      }
     ]
    },
    {
     "title": "GraphQL -- 95th percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tdg_graphql_query_time_bucket{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "95th percentile"
      }
     ]
    },
    {
     "title": "Success requests (code 2xx)",
     "type": "graph",
     "description": "Requests, processed with success (code 2xx) on Tarantool's side.\nGraph shows mean count per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "sum by (method, type) (rate(tdg_rest_result_200{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": " {{method}} {{type}} "
      }
     ]
    },
    {
     "title": "Error requests (code 4xx)",
     "type": "graph",
     "description": "Requests, processed with 4xx error on Tarantool's side.\nGraph shows mean count per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "sum by (method, type) (rate(tdg_rest_exec_time_count{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval]) - rate(tdg_rest_result_200{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{method}} -- {{type}}"
      }
     ]
    }
   ]
  },
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Cluster status overview",
   "type": "table-old",
   "description": "Overview of Tarantool instances, observed by Prometheus job.\n\nIf instance row is *red*, it means Prometheus can't reach URI specified in targets or ran into error.\nIf instance row is *green*, it means instance is up and running and\nPrometheus is successfully extracting metrics from it.\n\"Uptime\" column shows time since instant start.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "up{job=~\"$job\"} * on(instance) group_left(alias) tnt_info_uptime{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"} or\non(instance) label_replace(up{job=~\"$job\"} * tnt_info_uptime{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}, \"alias\", \"Not available\", \"instance\", \".*\")\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Count of running Tarantool instances, observed by Prometheus job.\nIf Prometheus can't reach URI specified in targets or ran into error, instance is not counted.\n",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\"$job\"} * on(instance) tnt_info_uptime{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Overall value of memory used by Tarantool items and indexes (*arena_used* value).\nIf Tarantool instance is not available for Prometheus metrics extraction now, its contribution is not counted.\n",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tnt_slab_arena_used{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Overall value of memory available for Tarantool items and indexes allocation (*memtx_memory* or *quota_size* values).\nIf Tarantool instance is not available for Prometheus metrics extraction now, its contribution is not counted.\n",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tnt_slab_quota_size{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Overall rate of HTTP requests processed on Tarantool instances (all methods and response codes).\nIf Tarantool instance is not available for Prometheus metrics extraction now, its contribution is not counted.\nIf `No data` displayed, check up your 'rate_time_range' variable.\n",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_latency_count{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Overall rate of network requests processed on Tarantool instances.\nIf Tarantool instance is not available for Prometheus metrics extraction now, its contribution is not counted.\nIf `No data` displayed, check up your 'rate_time_range' variable.\n",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(tnt_net_requests_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Overall rate of operations performed on Tarantool spaces (*select*, *insert*, *update* etc.).\nIf Tarantool instance is not available for Prometheus metrics extraction now, its contribution is not counted.\nIf `No data` displayed, check up your 'rate_time_range' variable.\n",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cartridge warning issues",
   "type": "graph",
   "description": "Number of \"warning\" issues on each cluster instance.\nPanel works with `cartridge >= 2.0.2`, `metrics >= 0.6.0`,\nwhile `metrics >= 0.9.0` is recommended for per instance display.\n\"warning\" issues includes high replication lag, replication long idle,\nfailover and switchover issues, clock issues, memory fragmentation,\nconfiguration issues and alien members warnings.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tnt_cartridge_issues{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",level=\"warning\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cartridge critical issues",
   "type": "graph",
   "description": "Number of \"critical\" issues on each cluster instance.\nPanel works with `cartridge >= 2.0.2`, `metrics >= 0.6.0`,\nwhile `metrics >= 0.9.0` is recommended for per instance display.\n\"critical\" issues includes replication process critical fails and\nrunning out of available memory.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tnt_cartridge_issues{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",level=\"critical\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Tarantool replication lag",
   "type": "graph",
   "description": "Replication lag value for Tarantool instance.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"tnt_replication_[[:digit:]]{1,2}_lag\", job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Tarantool HTTP statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success requests (code 2xx)",
     "type": "graph",
     "description": "Requests, processed with success (code 2xx) on Tarantool's side.\nGraph shows mean count per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_request_latency_count{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",status=~\"^2\\\\d{2}$\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Error requests (code 4xx)",
     "type": "graph",
     "description": "Requests, processed with 4xx error on Tarantool's side.\nGraph shows mean count per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_request_latency_count{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",status=~\"^4\\\\d{2}$\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Error requests (code 5xx)",
     "type": "graph",
     "description": "Requests, processed with 5xx error on Tarantool's side.\nGraph shows mean count per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_request_latency_count{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",status=~\"^5\\\\d{2}$\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Success requests latency (code 2xx)",
     "type": "graph",
     "description": "99th percentile of requests latency. Includes only requests processed with success (code 2xx) on Tarantool's side.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "99th percentile" }
     ],
     "targets": [
      {
       "expr": "http_server_request_latency{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",quantile=\"0.99\",status=~\"^2\\\\d{2}$\"}",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Error requests latency (code 4xx)",
     "type": "graph",
     "description": "99th percentile of requests latency. Includes only requests processed with 4xx error on Tarantool's side.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "99th percentile" }
     ],
     "targets": [
      {
       "expr": "http_server_request_latency{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",quantile=\"0.99\",status=~\"^4\\\\d{2}$\"}",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Error requests latency (code 5xx)",
     "type": "graph",
     "description": "99th percentile of requests latency. Includes only requests processed with 5xx error on Tarantool's side.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "99th percentile" }
     ],
     "targets": [
      {
       "expr": "http_server_request_latency{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",quantile=\"0.99\",status=~\"^5\\\\d{2}$\"}",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool network activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data received",
     "type": "graph",
     "description": "Data received by instance from binary protocol connections.\nGraph shows average bytes per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "Bps", "label": "received" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_net_received_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Data sent",
     "type": "graph",
     "description": "Data sent by instance with binary protocol connections.\nGraph shows average bytes per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "Bps", "label": "sent" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_net_sent_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Network requests handled",
     "type": "graph",
     "description": "Number of network requests this instance has handled.\nGraph shows mean rps.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_net_requests_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Network requests pending",
     "type": "graph",
     "description": "Number of pending network requests.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "none", "label": "pending" }
     ],
     "targets": [
      {
       "expr": "tnt_net_requests_current{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Binary protocol connections",
     "type": "graph",
     "description": "Number of current active network connections.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "none", "label": "current" }
     ],
     "targets": [
      {
       "expr": "tnt_net_connections_current{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool memtx allocation overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slab allocator monitoring information",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
     "options": {
      "content": "`quota_used_ratio` > 90%, `arena_used_ratio` > 90%, 50% < `items_used_ratio` < 90% – your memory is highly fragmented. See [docs](https://www.tarantool.io/en/doc/1.10/reference/reference_lua/box_slab/#lua-function.box.slab.info) for more info.\n\n`quota_used_ratio` > 90%, `arena_used_ratio` > 90%, `items_used_ratio` > 90% – you are running out of memory. You should consider increasing Tarantool’s memory limit (*box.cfg.memtx_memory*).\n"
     }
    },
    {
     "title": "Used by slab allocator (quota_used_ratio)",
     "type": "graph",
     "description": "`quota_used_ratio` = `quota_used` / `quota_size`.\n\n`quota_used` – used by slab allocator (for both tuple and index slabs).\n\n`quota_size` – memory limit for slab allocator (as configured in the *memtx_memory* parameter).\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent", "label": "used ratio" }
     ],
     "targets": [
      {
       "expr": "tnt_slab_quota_used_ratio{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used for tuples and indexes (arena_used_ratio)",
     "type": "graph",
     "description": "`arena_used_ratio` = `arena_used` / `arena_size`.\n\n`arena_used` – used for both tuples and indexes.\n\n`arena_size` – allocated for both tuples and indexes.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "percent", "label": "used ratio" }
     ],
     "targets": [
      {
       "expr": "tnt_slab_arena_used_ratio{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used for tuples (items_used_ratio)",
     "type": "graph",
     "description": "`items_used_ratio` = `items_used` / `items_size`.\n\n`items_used` – used only for tuples.\n\n`items_size` – allocated only for tuples.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "percent", "label": "used ratio" }
     ],
     "targets": [
      {
       "expr": "tnt_slab_items_used_ratio{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used by slab allocator (quota_used)",
     "type": "graph",
     "description": "Memory used by slab allocator (for both tuple and index slabs).\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes", "label": "in bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_slab_quota_used{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used for tuples and indexes (arena_used)",
     "type": "graph",
     "description": "Memory used for both tuples and indexes.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "bytes", "label": "in bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_slab_arena_used{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used for tuples (items_used)",
     "type": "graph",
     "description": "Memory used for only tuples.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "bytes", "label": "in bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_slab_items_used{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Slab allocator memory limit (quota_size)",
     "type": "graph",
     "description": "Memory limit for slab allocator (as configured in the *memtx_memory* parameter).\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes", "label": "in bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_slab_quota_size{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Allocated for tuples and indexes (arena_size)",
     "type": "graph",
     "description": "Memory allocated for both tuples and indexes by slab allocator.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "bytes", "label": "in bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_slab_arena_size{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Allocated for tuples (items_size)",
     "type": "graph",
     "description": "Memory allocated for only tuples by slab allocator.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "bytes", "label": "in bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_slab_items_size{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool vinyl statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vinyl disk data",
     "type": "graph",
     "description": "The amount of data stored in the `.run` files located in the `vinyl_dir` directory.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_vinyl_disk_data_size{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl index data",
     "type": "graph",
     "description": "The amount of data stored in the `.index` files located in the `vinyl_dir` directory.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_vinyl_disk_index_size{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator dump bandwidth",
     "type": "graph",
     "description": "The estimated average rate of taking dumps, bytes per second.\nInitially, the rate value is 10 megabytes per second\nand being recalculated depending on the the actual rate.\nOnly significant dumps that are larger than one megabyte\nare used for the estimate.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_dump_bandwidth{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator write rate",
     "type": "graph",
     "description": "The actual average rate of performing the write operations, bytes per second.\nThe rate is calculated as a 5-second moving average.\nIf the metric value is gradually going down, this can indicate some disk issues.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_write_rate{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator rate limit",
     "type": "graph",
     "description": "The write rate limit, bytes per second.\nThe regulator imposes the limit on transactions based on the observed dump/compaction performance.\nIf the metric value is down to approximately 100 Kbps,\nthis indicates issues with the disk or the scheduler.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_rate_limit{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator dump watermark",
     "type": "graph",
     "description": "The maximum amount of memory used for in-memory storing of a vinyl LSM tree.\nWhen accessing this maximum, the dumping must occur.\nFor details, see https://www.tarantool.io/en/doc/latest/book/box/engines/#engines-algorithm-filling-lsm.\nThe value is slightly smaller than the amount of memory allocated for vinyl trees,\nwhich is the `vinyl_memory` parameter.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_dump_watermark{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl tx commit rate",
     "type": "graph",
     "description": "Average per second rate of commits (successful transaction ends).\nIt includes implicit commits: for example, any insert operation causes a commit\nunless it is within a `box.begin()`–`box.commit()` block.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none", "label": "transactions per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_vinyl_tx_commit{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl tx rollback rate",
     "type": "graph",
     "description": "Average per second rate of rollbacks (unsuccessful transaction ends).\nThis is not merely a count of explicit `box.rollback()` requests — it includes requests\nthat ended with errors.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "none", "label": "transactions per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_vinyl_tx_rollback{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl tx conflict rate",
     "type": "graph",
     "description": "Average per second rate of conflicts that caused transactions to roll back.\nThe ratio `tx conflicts` / `tx commits` above 5% indicates that vinyl is not healthy.\nAt this moment you’ll probably see a lot of other problems with vinyl.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "none", "label": "transactions per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_vinyl_tx_conflict{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl read views",
     "type": "graph",
     "description": "Number of current read views, that is, transactions entered a read-only state\nto avoid conflict temporarily.\nIf the value stays non-zero for a long time, it indicates of a memory leak.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "none", "label": "current" }
     ],
     "targets": [
      {
       "expr": "tnt_vinyl_tx_read_views{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler tasks in progress",
     "type": "graph",
     "description": "The number of the scheduler dump/compaction tasks in progress now.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tnt_vinyl_scheduler_tasks{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\", status=\"inprogress\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler failed tasks rate",
     "type": "graph",
     "description": "Scheduler dump/compaction tasks failed.\nAverage per second rate is shown.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "none", "label": "per second rate" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_vinyl_scheduler_tasks{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",status=\"failed\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler dump time rate",
     "type": "graph",
     "description": "Time spent by all worker threads performing dumps.\nAverage per second rate is shown.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "per second rate" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_vinyl_scheduler_dump_time{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler dump count rate",
     "type": "graph",
     "description": "Scheduler dumps completed average per second rate.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "none", "label": "per second rate" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_vinyl_scheduler_dump_count{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool CPU statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU user time",
     "type": "graph",
     "description": "Panel works with `metrics >= 0.8.0`.\nThis is the average share of time\nspent by instance process executing in user mode.\nMetrics obtained using `getrusage()` call.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_cpu_user_time{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "CPU system time",
     "type": "graph",
     "description": "Panel works with `metrics >= 0.8.0`.\nThis is the average share of time\nspent by instance process executing in kernel mode.\nMetrics obtained using `getrusage()` call.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_cpu_system_time{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool memory miscellaneous",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lua runtime",
     "type": "graph",
     "description": "Memory used for the Lua runtime. Lua memory is bounded by 2 GB per instance. \n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes", "label": "in bytes" }
     ],
     "targets": [
      {
       "expr": "tnt_info_memory_lua{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool operations statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "SELECT space requests",
     "type": "graph",
     "description": "total count of SELECT requests to all instance spaces.\nGraph shows average requests per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"select\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "INSERT space requests",
     "type": "graph",
     "description": "total count of INSERT requests to all instance spaces.\nGraph shows average requests per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"insert\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "REPLACE space requests",
     "type": "graph",
     "description": "total count of REPLACE requests to all instance spaces.\nGraph shows average requests per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"replace\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "UPSERT space requests",
     "type": "graph",
     "description": "total count of UPSERT requests to all instance spaces.\nGraph shows average requests per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"upsert\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "UPDATE space requests",
     "type": "graph",
     "description": "total count of UPDATE requests to all instance spaces.\nGraph shows average requests per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"update\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "DELETE space requests",
     "type": "graph",
     "description": "total count of DELETE requests to all instance spaces.\nGraph shows average requests per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"delete\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Call requests",
     "type": "graph",
     "description": "Requests to execute stored procedures.\nGraph shows average requests per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"call\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Eval calls",
     "type": "graph",
     "description": "Calls to evaluate Lua code.\nGraph shows average requests per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"eval\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Request errors",
     "type": "graph",
     "description": "Requests resulted in error.\nGraph shows average errors per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "errors per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Authentication requests",
     "type": "graph",
     "description": "Authentication requests.\nGraph shows average errors per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"auth\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "SQL prepare calls",
     "type": "graph",
     "description": "SQL prepare calls. Panel works with Tarantool 2.x.\nGraph shows average errors per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"prepare\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "SQL execute calls",
     "type": "graph",
     "description": "SQL execute calls. Panel works with Tarantool 2.x.\nGraph shows average errors per second.\nIf `No data` displayed for Prometheus panel,\ncheck up your 'rate_time_range' variable.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "none", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{job=~\"$job\", ris_sub=~\"$zone\", alias=~\"$instance\",operation=\"execute\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  }
 ]
}