{
 "title": "AWCC-PostegreSQL",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "job", "query": "postgres_pgss" },
   { "name": "table_catalog", "query": "postgres" },
   {
    "name": "hostname",
    "query": "label_values(pg_up{job=~\"$job\"},hostname)"
   },
   {
    "name": "datname",
    "query": "label_values(pg_database_size{job=~\"$job\",hostname=~\"$hostname\",datname!~\"template.*\"},datname)"
   },
   {
    "name": "schema",
    "query": "label_values(pg_table_size_pg_table_size{hostname=~\"$hostname\", exporter_db_name=~\"$datname\"},schemaname)"
   },
   {
    "name": "table",
    "query": "label_values(pg_table_size_pg_table_size{hostname=~\"$hostname\", exporter_db_name=~\"$datname\"},relname)"
   },
   { "name": "rate", "query": "30s,1m,2m,5m,10m,15m,30m" },
   { "name": "main_pg_exporter_db", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Most important metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{job=\"$job\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{job=\"$job\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname=~\"$datname\"} / (pg_stat_database_blks_read{datname=~\"$datname\"} + pg_stat_database_blks_hit{datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pg_static{job=\"$job\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 9 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{job=\"$job\"} * 1000"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{job=\"$job\", datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_connections{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"$job\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{job=\"$job\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{job=\"$job\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{job=\"$job\"}"
    }
   ]
  },
  { "title": "PostgreSQL Database stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", job=\"$job\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{job=\"$job\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{job=\"$job\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", job=\"$job\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", job=\"$job\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", job=\"$job\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", job=\"$job\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", job=\"$job\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", job=\"$job\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", job=\"$job\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{job=\"$job\", datname=~\"$datname\"} / (pg_stat_database_blks_read{job=\"$job\", datname=~\"$datname\"} + pg_stat_database_blks_hit{job=\"$job\", datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{job=\"$job\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{job=\"$job\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{job=\"$job\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{job=\"$job\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{job=\"$job\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{job=\"$job\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{job=\"$job\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{job=\"$job\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{job=\"$job\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{job=\"$job\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  },
  { "title": "DB Connections, Locks, Rows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Database Connections by DB.User",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (usename, datname) (pg_database_connections_count{hostname=~\"$hostname\", datname=~\"$datname\"})",
     "legendFormat": "{{datname}}.{{usename}}"
    }
   ]
  },
  {
   "title": "Locks by type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{hostname=~\"$hostname\", datname=~\"$datname\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Rows fetched/returned",
   "type": "graph",
   "description": "Rate of rows(=tuples) fetched and returned by queries.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{hostname=~\"$hostname\", datname=~\"$datname\"}[$__rate_interval]))",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{hostname=~\"$hostname\", datname=~\"$datname\"}[$__rate_interval]))",
     "legendFormat": "returned"
    }
   ]
  },
  {
   "title": "Rows inserted/updated/deleted",
   "type": "graph",
   "description": "Rate of rows(=tuples) inserted, updated and deleted by queries.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{hostname=~\"$hostname\", datname=~\"$datname\"}[$__rate_interval]))",
     "legendFormat": "inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{hostname=~\"$hostname\", datname=~\"$datname\"}[$__rate_interval]))",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{hostname=~\"$hostname\", datname=~\"$datname\"}[$__rate_interval]))",
     "legendFormat": "deleted"
    }
   ]
  },
  { "title": "SQL Metrics: Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Active connections",
   "type": "graph",
   "description": "Current number of connected clients to each datname.\n\nCurrent number of backends. PostgreSQL creates a backend for each connected client.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{hostname=~\"$hostname\", datname=~\"$datname\"}",
     "legendFormat": "numbackends {{datname}} "
    },
    {
     "expr": "sum (pg_stat_database_numbackends{hostname=~\"$hostname\",datname=~\"$datname\"}) by (instance)",
     "legendFormat": "numbackends  {{datname}} "
    }
   ]
  },
  {
   "title": "Connections / Max DB connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(pg_stat_database_numbackends{hostname=~\"$hostname\"}))",
     "legendFormat": "backends"
    },
    {
     "expr": "sum(pg_settings_max_connections{hostname=~\"$hostname\"})",
     "legendFormat": "connections limit"
    }
   ]
  },
  {
   "title": "Connection activities",
   "type": "graph",
   "description": "Number of connections by state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{hostname=~\"$hostname\",datname=~\"$datname\"})",
     "legendFormat": "{{datname}} {{state}}"
    }
   ]
  },
  { "title": "SQL Metrics: Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Database size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size{datname=~\"$datname\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} Database {{datname}} size"
    }
   ]
  },
  {
   "title": "All tables idx scan",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_all_tables_idx_scan{hostname=~\"$hostname\"}",
     "legendFormat": "{{schemaname}}-{{relname}}"
    }
   ]
  },
  {
   "title": "Transaction stats",
   "type": "graph",
   "description": "Number of transactions that have been committed/rollbacked.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{hostname=~\"$hostname\", datname=~\"$datname\",datname=~\"$datname\"}[1m])",
     "legendFormat": "Committed transactions"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{hostname=~\"$hostname\",datname=~\"$datname\"}[1m])",
     "legendFormat": "Rollback transactions"
    }
   ]
  },
  { "title": "SQL Metrics: BGWriter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Bgwriter checkpoints",
   "type": "graph",
   "description": "A checkpoint is a point in WAL for which PostgreSQL ensures that all WAL-entries before the checkpoint are applied.\n\nCheckpoints are typically scheduled, but can be manually initiated.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_req{hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Requested checkpoints"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_timed{hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Scheduled checkpoints"
    }
   ]
  },
  {
   "title": "Bgwriter buffers",
   "type": "graph",
   "description": "The rate of how many dirty buffers are written down by a various subsystems: background writer, checkpointer or directly by a backend.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{hostname=~\"$hostname\"}[1m])",
     "legendFormat": "checkpointer"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_clean{hostname=~\"$hostname\"}[1m])",
     "legendFormat": "background writer"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_backend{hostname=~\"$hostname\"}[1m])",
     "legendFormat": "backend"
    }
   ]
  },
  { "title": "DEPRECATED Pg stat statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Total calls per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls{datname=~\"$datname\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{instance}} {{datname}} {{usename}} {{queryid}}"
    }
   ]
  },
  {
   "title": "Total time per user per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_total_time{datname=~\"$datname\",hostname=~\"$hostname\"}[1m])) by (hostname,usename,datname)",
     "legendFormat": "{{instance}} {{datname}} {{usename}} "
    },
    {
     "expr": "sum(rate(pg_stat_statements_total_time{datname=~\"$datname\",instance=~\"$instance\"}[1m])) by (instance,datname)",
     "legendFormat": "{{instance}} {{datname}}"
    }
   ]
  },
  {
   "title": "Mean time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(pg_stat_statements_total_time{datname=~\"$datname\",hostname=~\"$hostname\"}[5m])/delta(pg_stat_statements_calls{datname=~\"$datname\",hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{instance}} {{datname}} {{usename}} {{queryid}}"
    }
   ]
  },
  {
   "title": "Total time per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_total_time{datname=~\"$datname\",hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{instance}} {{datname}} {{usename}} {{queryid}}"
    }
   ]
  },
  {
   "title": "Returned rows per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "none", "label": "Row per minute" }
   ],
   "targets": [
    {
     "expr": "idelta(pg_stat_statements_rows{datname=~\"$datname\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{instance}} {{datname}} {{usename}} {{queryid}} "
    }
   ]
  }
 ]
}